import {promises as fs} from 'node:fs';
import JSZip from 'jszip';
import {DicomBinaryBuffer as B,exportMonacoRtStruct} from '../src/utils/monacoRtStructExporter';
import {importRtStruct,compareContours} from '../src/utils/rtStructImporter';
import {parseDicomByteArray} from '../src/utils/dicomParser';
import type {DicomSeries,StructureRoi} from '../src/types';
const uid=()=>`2.25.${BigInt('0x'+crypto.randomUUID().replaceAll('-',''))}`;
const studyUID=uid(),seriesUID=uid(),frameUID=uid(),n=64;
const series:DicomSeries={patientId:'RADCONTOUR_QA_MONACO6',patientName:'QA^SYNTHETIC^NO_CLINICAL',modality:'CT',studyDescription:'SYNTHETIC QA ONLY',seriesDescription:'Anisotropic phantom 1x2x3 mm',studyInstanceUID:studyUID,seriesInstanceUID:seriesUID,frameOfReferenceUID:frameUID,slices:Array.from({length:17},(_,z)=>({id:'qa-'+z,sliceIndex:z,rows:n,cols:n,pixelSpacing:[2,1],sliceThickness:3,sliceLocation:-24+z*3,imagePositionPatient:[-32,-64,-24+z*3],imageOrientationPatient:[1,0,0,0,1,0],huData:Int16Array.from({length:n*n},(_,i)=>Math.hypot(i%n-32,2*(Math.floor(i/n)-32))<26?0:-1000),minHU:-1000,maxHU:0,windowCenter:0,windowWidth:400,rescaleSlope:1,rescaleIntercept:0,sopInstanceUID:uid(),sopClassUID:'1.2.840.10008.5.1.4.1.1.2'}))};
function ct(z:number){const s=series.slices[z],b=new B(),str=(g:number,e:number,vr:string,v:string)=>b.writeStringElement(g,e,vr,v),us=(g:number,e:number,v:number)=>b.writeElement(g,e,'US',new Uint8Array([v&255,v>>8]));
str(8,5,'CS','ISO_IR 192');str(8,8,'CS','DERIVED\\SECONDARY\\AXIAL');str(8,0x16,'UI',s.sopClassUID!);str(8,0x18,'UI',s.sopInstanceUID!);str(8,0x20,'DA','20260908');str(8,0x30,'TM','120000');str(8,0x50,'SH','QA_ONLY');str(8,0x60,'CS','CT');str(8,0x70,'LO','RadContour');str(8,0x90,'PN','');str(8,0x1030,'LO',series.studyDescription);str(8,0x103e,'LO',series.seriesDescription);
str(0x10,0x10,'PN',series.patientName);str(0x10,0x20,'LO',series.patientId);str(0x10,0x30,'DA','');str(0x10,0x40,'CS','');str(0x18,0x50,'DS','3');str(0x18,0x60,'DS','120');str(0x18,0x5100,'CS','HFS');str(0x20,0x0d,'UI',studyUID);str(0x20,0x0e,'UI',seriesUID);str(0x20,0x10,'SH','QA6');str(0x20,0x11,'IS','1');str(0x20,0x13,'IS',String(z+1));str(0x20,0x32,'DS',s.imagePositionPatient.join('\\'));str(0x20,0x37,'DS','1\\0\\0\\0\\1\\0');str(0x20,0x52,'UI',frameUID);str(0x20,0x1040,'LO','');str(0x20,0x1041,'DS',String(s.sliceLocation));us(0x28,2,1);str(0x28,4,'CS','MONOCHROME2');us(0x28,0x10,n);us(0x28,0x11,n);str(0x28,0x30,'DS','2\\1');for(const [e,v] of [[0x100,16],[0x101,16],[0x102,15],[0x103,1]])us(0x28,e,v);str(0x28,0x1050,'DS','0');str(0x28,0x1051,'DS','400');str(0x28,0x1052,'DS','0');str(0x28,0x1053,'DS','1');str(0x28,0x1054,'LO','HU');b.writeElement(0x7fe0,0x10,'OW',new Uint8Array(s.huData.buffer));
const meta=new B();meta.writeElement(2,1,'OB',new Uint8Array([0,1]));for(const [e,v] of [[2,s.sopClassUID!],[3,s.sopInstanceUID!],[0x10,'1.2.840.10008.1.2.1'],[0x12,'2.25.20987259671081357965317975913516658534']] as const)meta.writeStringElement(2,e,'UI',v);const f=new B();f.writeBytes(new Uint8Array(128));f.writeAsciiString('DICM');f.writeUint16(2);f.writeUint16(0);f.writeAsciiString('UL');f.writeUint16(4);f.writeUint32(meta.getBytes().length);f.writeBytes(meta.getBytes());f.writeBytes(b.getBytes());return f.getBytes();}
const shapes:Record<string,(x:number,y:number,z:number)=>boolean>={BOX:(x,y,z)=>Math.abs(x)<8 && Math.abs(y)<12 && Math.abs(z)<9,SPHERE:(x,y,z)=>x*x+y*y+z*z<=100,CYLINDER:(x,y,z)=>x*x+y*y<=100 && Math.abs(z)<=9,RING_ISLAND:(x,y,z)=>Math.abs(z)<=6 && ((x*x+y*y>=64 && x*x+y*y<=225) || (x===0 && y===0)),SINGLE_VOXEL:(x,y,z)=>x===20 && y===0 && z===0};
const rois:StructureRoi[]=Object.entries(shapes).map(([name,fn])=>({id:uid(),name,type:'OAR',color:'#22cc88',visible:true,locked:false,opacity:.4,sliceMasks:Object.fromEntries(series.slices.map((s,z)=>[z,Uint8Array.from({length:n*n},(_,i)=>Number(fn(i%n-32,2*(Math.floor(i/n)-32),3*(z-8))))]))}));
const zip=new JSZip();for(let z=0;z<series.slices.length;z++){const bytes=ct(z),parsed=parseDicomByteArray(bytes);if(parsed.seriesInfo.patientId!==series.patientId || parsed.slice.huData[0]!==-1000)throw new Error('CT phantom failed roundtrip');zip.file(`CT/CT_${String(z+1).padStart(3,'0')}.dcm`,bytes);}
const reports={};for(const holeMode of ['keyhole','xor'] as const){const result=exportMonacoRtStruct(series,rois,{holeMode,structureSetLabel:holeMode==='keyhole'?'QA6_KEYHOLE':'QA6_XOR'}),bytes=new Uint8Array(await result.blob.arrayBuffer());const comparison=compareContours(rois,importRtStruct(bytes,series),series);if(comparison.some(r=>r.dice!==1))throw new Error('Phantom export mismatch');reports[holeMode]=comparison;zip.file(`RTSTRUCT_${holeMode.toUpperCase()}.dcm`,bytes);}
zip.file('expected-local.json',JSON.stringify({patientId:series.patientId,spacingMm:[1,2,3],note:'Voxelized reference volumes; TPS contours may integrate slice ends differently. Import each RTSTRUCT separately.',reports},null,2));
zip.file('PROTOCOLO_MONACO_6.md',await fs.readFile('docs/MONACO_6.md'));
await fs.mkdir('validation',{recursive:true});await fs.writeFile('validation/Monaco6-QA.zip',await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'}));console.log('Created synthetic Monaco6-QA.zip: 17 CT slices, 5 ROIs, two RTSTRUCT encodings, exact local roundtrip.');
