import React,{lazy,Suspense} from 'react';
import type {DicomSeries,ImageStudy,MprCoordinates,StructureRoi,RegistrationState} from '../types';
import {ImagePlane} from '../utils/panelPlane';
import {tr} from '../i18n';
const Contours3D=lazy(()=>import('./Contours3D'));
export interface PaneConfig {plane:ImagePlane|'3d'|'controls'|'detail';mode:string;secondaryId?:string;}
export const defaultPanes:PaneConfig[]=[{plane:'axial',mode:'reference'},{plane:'sagittal',mode:'reference'},{plane:'coronal',mode:'reference'},{plane:'detail',mode:'reference'}];
interface Props {renderEditor:(plane:ImagePlane,config:PaneConfig,secondaryId?:string)=>React.ReactNode;showCrosshairs?:boolean;onToggleCrosshairs?:()=>void;onActivate?:(p:ImagePlane)=>void;config:PaneConfig;onChange:(p:PaneConfig)=>void;index:number;series:DicomSeries|null;studies:ImageStudy[];coordinates:MprCoordinates;onNavigate:(p:Partial<MprCoordinates>)=>void;rois:StructureRoi[];activeRoiId?:string;registration?:RegistrationState;windowCenter:number;windowWidth:number;controls:React.ReactNode;editor?:React.ReactNode;detailPlane:ImagePlane;}
export function ConfigurablePane(props:Props){
 const {config,onChange,index,series,studies,registration,editor,controls}=props;
 const secondary=studies.filter(s=>s.id!==registration?.referenceStudyId && s.slices!==series?.slices && (registration?.transforms[s.id]?.model==='rigid3d' || (!!s.frameOfReferenceUID && s.frameOfReferenceUID===series?.frameOfReferenceUID)));
 const picked=secondary.find(s=>s.id===(config.secondaryId || registration?.secondaryStudyId)) || secondary[0];
 const plane=config.plane==='detail'?props.detailPlane:config.plane;
 return <section className="flex flex-col flex-1 min-h-0 min-w-0 overflow-hidden bg-black border border-zinc-800" data-testid={'view-pane-'+index} onPointerEnter={()=>{if(['axial','coronal','sagittal'].includes(config.plane))props.onActivate?.(config.plane as ImagePlane);}}><header className="flex items-center flex-wrap gap-1 text-xs bg-zinc-950 p-1 shrink-0"><select aria-label={tr('Contenido del panel')+' '+(index+1)} className="bg-zinc-800 rounded max-w-full" value={config.plane} onChange={e=>onChange({...config,plane:e.target.value as PaneConfig['plane']})}>{[['axial','Axial'],['coronal','Coronal'],['sagittal','Sagital'],['detail','Detalle del plano activo'],['3d','Contornos 3D'],['controls','Controles']].map(([v,label])=><option key={v} value={v}>{tr(label)}</option>)}</select>{plane!=='3d' && plane!=='controls' && <><select aria-label={tr('Modo del panel')+' '+(index+1)} value={config.mode} className="bg-zinc-800 rounded" onChange={e=>onChange({...config,mode:e.target.value})}>{[['reference','Referencia'],['secondary','Secundaria alineada'],['blend','Fusión'],['compare','Comparar secundaria'],['checkerboard','Tablero'],['split_horizontal','División izquierda/derecha'],['split_vertical','División superior/inferior'],['difference','Diferencia']].map(([v,label])=><option key={v} value={v} disabled={v!=='reference' && !picked}>{tr(label)}</option>)}</select>{config.mode!=='reference' && <select aria-label={tr('Imagen secundaria')+' '+(index+1)} className="bg-zinc-800 max-w-40" value={picked?.id || ''} onChange={e=>onChange({...config,secondaryId:e.target.value})}>{secondary.map(s=><option key={s.id} value={s.id}>{s.modality} · {s.seriesDescription}</option>)}</select>}</>}</header>
 {plane==='3d'?(series?<Suspense fallback={<p>{tr('Cargando vista 3D…')}</p>}><Contours3D series={series} rois={props.rois} activeRoiId={props.activeRoiId}/></Suspense>:null):plane==='controls'?controls:props.renderEditor(plane as ImagePlane,config,picked?.id)}
 </section>;
}