import React,{useState} from 'react';
import {ImportSeries} from '../utils/dicomParser';
import {tr} from '../i18n';
export function DicomImportModal({groups,onClose,onLoad}:{groups:ImportSeries[];onClose:()=>void;onLoad:(groups:ImportSeries[])=>void}){
 const [selected,setSelected]=useState<string[]>([]),[accepted,setAccepted]=useState(false);
 const chosen=groups.filter(g=>selected.includes(g.key)),compressed=chosen.some(g=>g.compressed || g.lossy);
 const patients=new Set(chosen.map(g=>g.patientId));
 return <div className="fixed inset-0 z-[100] bg-black/70 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-labelledby="dicom-import-title" className="bg-zinc-900 border border-zinc-600 rounded-lg p-5 w-full max-w-3xl max-h-[90vh] overflow-auto text-zinc-100 space-y-4">
  <h2 id="dicom-import-title" className="text-lg font-semibold">{tr('Seleccionar series DICOM')}</h2>
  <p className="text-sm text-zinc-400">{tr('Seleccione las series de un paciente. Solo se cargarán y archivarán las imágenes seleccionadas.')}</p>
  <div className="space-y-2">{groups.map(g=><label key={g.key} className="flex gap-3 p-3 border border-zinc-700 rounded items-start"><input type="checkbox" disabled={g.unsupported} checked={selected.includes(g.key)} onChange={e=>{setSelected(e.target.checked?[...selected,g.key]:selected.filter(k=>k!==g.key));setAccepted(false);}}/><span className="min-w-0 break-words text-sm"><strong>{g.patientId} · {g.patientName}</strong><br/>{g.modality} · {g.description} · {g.frames ?? g.files.length} {tr('imágenes')}{g.enhanced && <span className="block text-cyan-300">{tr('Enhanced DICOM · selección por volumen')}</span>}{g.raw && <span className="block text-cyan-300">{tr('DICOM sin cabecera Part 10')}</span>}<br/><span className={g.compressed || g.lossy?'text-amber-300':'text-zinc-400'}>{g.lossy?tr('Compresión con pérdida o no determinada'):g.compressed?tr('Compresión sin pérdida'):tr('Sin compresión')}</span>{g.unsupported && <span className="text-red-300"> · {tr('Formato no compatible (sintaxis, color o multiframe)')}</span>}<span className="block text-xs text-zinc-500">{g.syntaxes.join(', ')}</span></span></label>)}</div>
  {chosen.some(g=>g.enhanced) && <p className="text-sm text-amber-200">{tr('Se cargarán los volúmenes seleccionados. El archivo Enhanced original se conserva completo, incluidos los cuadros de otras fases que contenga.')}</p>}
  {compressed && <div className="p-3 border border-amber-600 rounded text-sm text-amber-200 space-y-2"><p>{tr('Estas imágenes proceden de DICOM comprimidos. Pueden utilizarse para contouring y corregistro tras su decodificación, pero podrían no ser aptas para cálculo de dosis en TPS. La compresión sin pérdida conserva los valores; la compresión con pérdida puede alterarlos. Descomprimir no recupera información perdida ni certifica la imagen para cálculo. Verifique los originales y la compatibilidad del TPS.')}</p><label className="flex gap-2"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{tr('Entiendo la advertencia sobre cálculo en TPS.')}</label></div>}
  {patients.size>1 && <p className="text-amber-300">{tr('Seleccione series de un solo paciente por importación.')}</p>}
  <div className="flex justify-end gap-2"><button className="px-3 py-2 border rounded" onClick={onClose}>{tr('Cancelar')}</button><button className="px-3 py-2 rounded bg-blue-600 disabled:opacity-40" disabled={!chosen.length || patients.size>1 || (compressed && !accepted)} onClick={()=>onLoad(chosen)}>{tr('Cargar series seleccionadas')}</button></div>
 </section></div>;
}
