import {tr,useLanguage} from '../i18n';
import React,{useState,useEffect} from 'react';
import {libraryIndex,filterPatients,removeLibraryEntry,restoreLibraryEntry,LibraryIndex} from '../utils/libraryClient';
import {prepareBulk,downloadBulk} from '../utils/bulkExport';

export function LibraryManager(){
  useLanguage();
  const [index,setIndex]=useState<LibraryIndex|null>(null),[query,setQuery]=useState(''),[selection,setSelection]=useState<string[]>([]);
  const [prepared,setPrepared]=useState<any>(null),[tolerance,setTolerance]=useState(0),[area,setArea]=useState(0),[roiNames,setRoiNames]=useState(''),[holeMode,setHoleMode]=useState('keyhole'),[accepted,setAccepted]=useState(false);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[trash,setTrash]=useState(false),[originals,setOriginals]=useState(false);
  useEffect(()=>{setPrepared(null);setAccepted(false);},[selection,originals,tolerance,area,roiNames,holeMode]);
  const refresh=async()=>{const next=await libraryIndex();setIndex(next);setSelection(prev=>{const kept=prev.filter(k=>next.patients.some(p=>p.studies.some(s=>s.key===k)));return kept.length===prev.length?prev:kept;});};
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
  const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const remove=(kind:'patient'|'study',key:string,label:string)=>{
    if(!window.confirm(tr('¿Eliminar {0} de la biblioteca? Sus imágenes y contornos pasarán a la papelera. Si está abierto en contouring, cierre ese caso sin guardar. Puede restaurarlo desde aquí.',[label])))return;
    void action(async()=>{await removeLibraryEntry(kind,key);setMessage(tr("Eliminado de la biblioteca. Puede restaurarlo en Papelera."));});
  };
  const patients=filterPatients(index?.patients || [],query).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));
  const toggle=(key:string)=>setSelection(prev=>prev.includes(key)?prev.filter(k=>k!==key):[...prev,key]);
  const exportSelected=()=>void action(async()=>{
    const result=await downloadBulk(prepared,setMessage);
    const url=URL.createObjectURL(result.blob),link=document.createElement('a');link.href=url;link.download=`TPS_${new Date().toISOString().replace(/[:.]/g,'-')}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
    setMessage(tr("{0} estudios exportados; {1} omitidos. Consulte informe.json dentro del ZIP.", [result.report.filter(r=>r.status==='exportado').length,result.report.filter(r=>r.status==='omitido').length]));
  });
  const button='border border-zinc-600 rounded px-3 py-2 hover:bg-zinc-800 disabled:opacity-40';
  return <main className="h-screen overflow-auto bg-[#101114] text-zinc-200 p-6 text-sm">
    <div className="max-w-6xl mx-auto space-y-5">
      <header className="flex items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">{" "}IVCS RT · {tr("Biblioteca local")}{" "}</h1><p className="text-zinc-400 mt-1">{" "}{tr("Pacientes, imágenes y exportación para TPS")}{" "}</p></div><a href="/" className={button}>{" "}{tr("Ir a contouring")}{" "}</a></header>
      <div className="flex flex-wrap gap-2"><input aria-label={tr("Filtrar biblioteca")} className="flex-1 min-w-64 bg-zinc-900 border border-zinc-600 rounded px-3 py-2" placeholder={tr("ID, nombre, apellidos, modalidad o fecha…")} value={query} onChange={e=>setQuery(e.target.value)}/><button className={button} disabled={busy} onClick={()=>void action(refresh)}>{" "}{tr("Actualizar")}{" "}</button><button className={button} disabled={busy} onClick={()=>setTrash(!trash)}>{trash?tr("Volver a pacientes"):tr("Papelera ({0})", [index?.trash?.length || 0])}</button></div>
      {error && <p role="alert" className="text-red-300 bg-red-950/40 p-3 rounded">{" "}{tr(error)}{" "}</p>}
      {message && <p role="status" className="text-blue-200 bg-blue-950/40 p-3 rounded">{" "}{tr(message)}{" "}</p>}
      {!trash && <>
        <div className="flex flex-wrap items-center gap-3 border border-zinc-700 p-3 rounded"><button className={button} disabled={busy} onClick={()=>setSelection(patients.flatMap(p=>p.studies.map(s=>s.key)))}>{" "}{tr("Seleccionar filtrados")}{" "}</button><button className={button} disabled={busy} onClick={()=>setSelection([])}>{" "}{tr("Limpiar selección")}{" "}</button><span>{selection.length}{" "}{tr("series seleccionadas")}{" "}</span><label className="flex gap-2"><input type="checkbox" checked={originals} disabled={busy} onChange={e=>setOriginals(e.target.checked)}/>{" "}{tr("Incluir DICOM originales")}{" "}</label><button className="rounded bg-blue-700 hover:bg-blue-600 px-4 py-2 disabled:opacity-40" disabled={busy || !selection.length} onClick={()=>void action(async()=>{setPrepared(await prepareBulk(index!.patients,selection,originals,{pointToleranceMm:tolerance,minContourAreaMm2:area,holeMode:holeMode as any,roiNames:roiNames.split(',').map(s=>s.trim()).filter(Boolean)},setMessage));setMessage('Comprobación finalizada. Revise los resultados antes de descargar.');})}>{" "}{tr("Comprobar selección para TPS")}{" "}</button></div>
        <div className="flex flex-wrap gap-3 text-xs"><label>{" "}{tr("Tolerancia mm")}{" "}<input className="bg-zinc-800 w-20 p-1" disabled={busy} type="number" min="0" step="0.1" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label><label>{" "}{tr("Área mínima mm²")}{" "}<input className="bg-zinc-800 w-20 p-1" disabled={busy} type="number" min="0" step="0.1" value={area} onChange={e=>setArea(Number(e.target.value))}/></label><label>{" "}{tr("Huecos")}{" "}<select disabled={busy} className="bg-zinc-800 p-1" value={holeMode} onChange={e=>setHoleMode(e.target.value)}><option value="keyhole">{" "}{tr("Keyhole")}{" "}</option><option value="xor">{" "}{tr("XOR (verificar TPS)")}{" "}</option></select></label><input disabled={busy} aria-label={tr("Nombres de ROI a exportar")} className="bg-zinc-800 p-1 flex-1" placeholder={tr("ROI separadas por coma; vacío = todas")} value={roiNames} onChange={e=>setRoiNames(e.target.value)}/></div>
        {prepared && <div className="border border-blue-800 p-3 rounded space-y-2"><h2>{" "}{tr("Resultado de la comprobación")}{" "}</h2>{prepared.report.map((r,i)=><div key={i} className="text-xs"><strong>{r.patientId} · {r.study}: {tr(r.status)}</strong> · {tr(r.detail)}{r.comparison?.map(c=><p key={c.name} className={c.changedSlices.length?'text-amber-300':'text-zinc-400'}>{c.name}{" "}{tr(": Dice")}{" "}{c.dice.toFixed(5)}{" "}{tr("· Δ volumen")}{" "}{(c.volumeAfter-c.volumeBefore).toFixed(3)}{" "}{tr("cm³ · cortes modificados:")}{" "}{c.changedSlices.join(', ') || tr("ninguno")}</p>)}</div>)}<label className="block text-xs"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{" "}{tr("He revisado las omisiones y diferencias.")}{" "}</label><button className={button} disabled={busy || !accepted || !prepared.cases.length} onClick={exportSelected}>{" "}{tr("Descargar ZIP para TPS")}{" "}</button></div>}
        <p className="text-xs text-zinc-400">{" "}{tr("Se exporta la última versión guardada de cada serie. Guarde en contouring antes de exportar. ZIP con RTSTRUCT por serie e informe de resultados. Sin filtros por defecto para conservar estructuras pequeñas.")}{" "}</p>
        {!patients.length && <p className="p-8 text-center text-zinc-400">{index?tr("No hay pacientes que coincidan. Importe las imágenes desde contouring."):tr("Cargando biblioteca…")}</p>}
        {patients.map(p=><section key={p.key} className="border border-zinc-700 rounded overflow-hidden"><div className="bg-zinc-900 p-3 flex items-center justify-between"><div><strong className="font-mono text-blue-300">{p.id}</strong><span className="ml-4">{p.name.replace(/\^/g,' ') || tr("Sin nombre")}</span></div><button disabled={busy} className="text-red-300 text-xs" onClick={()=>remove('patient',p.key,`al paciente ${p.id} y sus ${p.studies.length} series`)}>{" "}{tr("Eliminar paciente")}{" "}</button></div>
          {p.studies.map(s=><div key={s.key} className="p-3 border-t border-zinc-800 flex items-center gap-3"><input aria-label={tr("Seleccionar {0} {1}", [p.id,s.description || s.id])} type="checkbox" disabled={busy} checked={selection.includes(s.key)} onChange={()=>toggle(s.key)}/><div className="flex-1"><div><strong>{s.modality}</strong> · {s.description || s.studyDescription || tr("Sin descripción")}</div><div className="text-xs text-zinc-400 mt-1">{s.date || tr("Sin fecha")} · {s.slices}{" "}{tr("cortes ·")}{" "}{s.originals}{" "}{tr("DICOM originales ·")}{" "}{s.state?tr("Contornos guardados"):tr("Sin sesión guardada")}</div></div><div className="flex gap-2">{p.groups.filter(g=>g.members.includes(s.key)).map(g=><span key={g.id} title={g.label} className="w-3 h-3 rounded-full" style={{backgroundColor:g.color}}/>)}</div><button disabled={busy} className="text-red-300 text-xs" onClick={()=>remove('study',s.key,tr('la serie {0} del paciente {1}',[s.description || s.modality,p.id]))}>{" "}{tr("Eliminar estudio")}{" "}</button></div>)}
        </section>)}
      </>}
      {trash && <><p className="text-zinc-400">{" "}{tr("Los elementos eliminados no aparecen en la biblioteca. Se conservan en la carpeta portable para poder recuperarlos; todavía ocupan espacio.")}{" "}</p>{!index?.trash?.length && <p>{" "}{tr("Papelera vacía.")}{" "}</p>}{index?.trash?.map(t=><div key={t.id} className="border border-zinc-700 rounded p-4 flex justify-between"><div><strong>{t.patient.id}</strong> · {t.patient.name.replace(/\^/g,' ')}<p className="text-xs text-zinc-400">{t.patient.studies.map(s=>s.description || s.modality).join(', ')} · {new Date(t.deletedAt).toLocaleString()}</p></div><button className={button} disabled={busy} onClick={()=>void action(async()=>{await restoreLibraryEntry(t.id);setMessage('Restaurado en la biblioteca.');})}>{" "}{tr("Restaurar")}{" "}</button></div>)}</>}
      <footer className="text-xs text-zinc-500 break-all pb-6">{" "}{tr("Carpeta de casos:")}{" "}{index?.folder || '…'}</footer>
    </div>
  </main>;
}
