import {tr} from '../i18n';
import React,{useEffect,useRef,useState} from 'react';
import type {DicomSeries,StructureRoi,ImageStudy,RegistrationState} from '../types';
import {bundleCatalog,buildDicomBundle,BundleCatalog} from '../utils/dicomBundle';
import {compute} from '../utils/computeClient';
import {renderSliceToCanvas} from '../utils/registrationEngine';
export function DifferencePreview({series,original,restored}:{series:DicomSeries;original:StructureRoi;restored:StructureRoi}){
  const [z,setZ]=useState(0),canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=canvas.current,s=series.slices[z];if(!c || !s)return;c.width=s.cols;c.height=s.rows;const ctx=c.getContext('2d')!;ctx.drawImage(renderSliceToCanvas(s,s.windowCenter,s.windowWidth,'grayscale'),0,0);const pixels=ctx.getImageData(0,0,c.width,c.height),a=original.sliceMasks[z],b=restored.sliceMasks[z];for(let i=0;i<c.width*c.height;i++){if(a?.[i] || b?.[i]){const color=a?.[i] && b?.[i]?[0,200,80]:a?.[i]?[255,50,50]:[0,180,255];for(let k=0;k<3;k++)pixels.data[4*i+k]=.4*pixels.data[4*i+k]+.6*color[k];}}ctx.putImageData(pixels,0,0);},[series,original,restored,z]);
  return <div><p className="text-xs">{" "}{tr("Corte")}{" "}{z+1}{" "}{tr("· Verde: coincide · Rojo: perdido · Azul: añadido")}{" "}</p><canvas ref={canvas} style={{aspectRatio:`${series.slices[z].cols*series.slices[z].pixelSpacing[1]} / ${series.slices[z].rows*series.slices[z].pixelSpacing[0]}`}} className="max-h-64 w-auto max-w-full mx-auto"/><input aria-label={tr("Corte de comparación RTSTRUCT")} type="range" min="0" max={series.slices.length-1} value={z} onChange={e=>setZ(Number(e.target.value))} className="w-full"/></div>;
}
export function MonacoExportModal({isOpen,onClose,series,rois,mode='rtstruct',studies=[],registration}:{isOpen:boolean;onClose:()=>void;series:DicomSeries|null;rois:StructureRoi[];mode?:'rtstruct'|'zip'|'advanced';studies?:ImageStudy[];registration?:RegistrationState}){
  const [tolerance,setTolerance]=useState(0),[area,setArea]=useState(0),[holeMode,setHoleMode]=useState('keyhole'),[selected,setSelected]=useState<string[]>(rois.map(r=>r.id)),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[previewIndex,setPreviewIndex]=useState(0),abort=useRef<AbortController|null>(null);
  const [catalog,setCatalog]=useState<BundleCatalog|null>(null),[extras,setExtras]=useState<string[]>([]),[catalogError,setCatalogError]=useState(''),[packing,setPacking]=useState(false),[progress,setProgress]=useState('');
  useEffect(()=>{if(mode==='rtstruct' || !series || !registration)return;let cancelled=false;setCatalog(null);setCatalogError('');setExtras([]);bundleCatalog(series,studies,registration).then(value=>{if(!cancelled)setCatalog(value);}).catch(e=>{if(!cancelled)setCatalogError(e.message);});return()=>{cancelled=true;};},[mode,series,studies,registration]);
  useEffect(()=>()=>abort.current?.abort(),[]);
  useEffect(()=>{setResult(null);setAccepted(false);},[selected,tolerance,area,holeMode,rois]);
  if(!isOpen || !series)return null;
  const chosen=rois.filter(r=>selected.includes(r.id)),eligible=chosen.filter(r=>Object.values(r.sliceMasks).some(m=>m.some(v=>v)));
  const preflight=async()=>{setBusy(true);setError('');setResult(null);setAccepted(false);abort.current=new AbortController();try{const names=chosen.map(r=>r.name.trim().toLowerCase());if(new Set(names).size!==names.length)throw new Error('Hay nombres de estructuras duplicados. Renómbrelos antes de exportar.');setResult(await compute('export',[series,chosen,{pointToleranceMm:tolerance,minContourAreaMm2:area,holeMode}],{signal:abort.current.signal}));setPreviewIndex(0);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const download=async()=>{setError('');setBusy(true);setPacking(true);abort.current=new AbortController();try{
    const blob=mode==='rtstruct'?result.blob:await buildDicomBundle(series,result.blob,catalog!,mode==='advanced'?extras:[],setProgress,abort.current.signal);
    const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=mode==='rtstruct'?result.fileName:(mode==='advanced'?'DICOM_advanced.zip':'DICOM.zip');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);
  }catch(e){setError((e as Error).message);}finally{setBusy(false);setPacking(false);setProgress('');}};
  const changed=result?.comparison.some(r=>r.changedSlices.length),button='px-3 py-2 rounded border border-zinc-600 hover:bg-zinc-800 disabled:opacity-40';
  return <div className="fixed inset-0 z-50 bg-black/75 flex items-center justify-center p-3"><section role="dialog" aria-modal="true" aria-label={tr(mode==='rtstruct'?'Exportar RTSTRUCT para TPS':mode==='zip'?'DICOM .zip':'DICOM .zip avanzado')} className="bg-zinc-950 border border-zinc-600 rounded-xl text-zinc-200 p-5 max-w-4xl w-full max-h-[95vh] overflow-auto space-y-3"><header className="flex justify-between"><div><h2 className="font-semibold">{" "}{tr(mode==='rtstruct'?'Exportar RTSTRUCT para TPS':mode==='zip'?'DICOM .zip':'DICOM .zip avanzado')}{" "}</h2><p className="text-xs text-zinc-400">{series.patientId} · {series.patientName} · {series.seriesDescription}</p></div><button className={button} disabled={busy} onClick={onClose}>{" "}{tr("Cerrar")}{" "}</button></header>
    {mode!=='rtstruct' && <div className="border border-zinc-700 rounded p-3 space-y-2 text-xs"><p>{tr('Incluye las imágenes originales de la serie principal y los contornos actuales seleccionados, incluso sin guardar la sesión.')}</p>{catalogError && <p role="alert" className="text-amber-300">{tr(catalogError)}</p>}{!catalog && !catalogError && <p>{tr('Consultando originales…')}</p>}{mode==='advanced' && <><p>{tr('Seleccione las series adicionales. Se incluirán sus originales y el corregistro rígido 3D en archivos DICOM REG. El TPS debe admitir REG; compruebe la alineación después de importar.')}</p><div className="max-h-40 overflow-auto space-y-2">{catalog?.choices.map(c=><label key={c.entry.key} className="block"><input type="checkbox" disabled={busy || !!c.reason} checked={extras.includes(c.entry.key)} onChange={e=>setExtras(e.target.checked?[...extras,c.entry.key]:extras.filter(k=>k!==c.entry.key))}/> {c.entry.modality} · {c.entry.description} · {c.entry.slices} {tr('imágenes')} <span className={c.reason?'text-amber-300':'text-zinc-400'}>— {tr(c.reason || c.source || '')}</span></label>)}{catalog && !catalog.choices.length && <p>{tr('No hay otras series disponibles para este paciente.')}</p>}</div></>}</div>}
    {series.slices.some(s=>s.sourceCompressed || s.sourceLossy) && <p className="text-sm text-amber-300">{tr('Origen DICOM comprimido: verifique los originales antes del cálculo de dosis en TPS. Exportar contornos no valida la imagen para cálculo.')}</p>}
    <div className="flex flex-wrap gap-3 text-xs"><label>{" "}{tr("Tolerancia (mm)")}{" "}<input aria-label={tr("Tolerancia de exportación")} disabled={busy} type="number" min="0" step="0.1" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))} className="block bg-zinc-800 p-2 w-24"/></label><label>{" "}{tr("Área mínima (mm²)")}{" "}<input aria-label={tr("Área mínima de exportación")} disabled={busy} type="number" min="0" step="0.1" value={area} onChange={e=>setArea(Number(e.target.value))} className="block bg-zinc-800 p-2 w-24"/></label><label>{" "}{tr("Huecos")}{" "}<select disabled={busy} aria-label={tr("Representación de huecos")} className="block bg-zinc-800 p-2" value={holeMode} onChange={e=>setHoleMode(e.target.value)}><option value="keyhole">{" "}{tr("CLOSED_PLANAR con keyhole")}{" "}</option><option value="xor">{" "}{tr("CLOSEDPLANAR_XOR (verificar soporte TPS)")}{" "}</option></select></label></div>
    <p className="text-xs text-zinc-400">{" "}{tr("Por defecto se conserva cada vóxel, incluidas estructuras pequeñas. El suavizado solo se acepta si mantiene la máscara. La comprobación local no sustituye la importación de prueba en su versión de TPS.")}{" "}</p>
    <div className="flex flex-wrap gap-3 max-h-36 overflow-auto text-xs">{rois.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} disabled={busy} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/> {r.name}</label>)}</div>
    {error && <p role="alert" className="text-red-300">{" "}{tr(error)}{" "}</p>}
    <button className={button} disabled={busy || !eligible.length || (mode!=='rtstruct' && !catalog)} onClick={()=>void preflight()}>{busy?tr(packing?progress:"Comprobando geometría…"):tr("Comprobar antes de exportar")}</button>{busy && <button className={button} onClick={()=>abort.current?.abort()}>{" "}{tr("Cancelar cálculo")}{" "}</button>}
    {result && <><table className="w-full text-xs"><thead><tr><th>{" "}{tr("ROI")}{" "}</th><th>{" "}{tr("Volumen original → reconstruido (cm³)")}{" "}</th><th>{" "}{tr("Dice")}{" "}</th><th>{" "}{tr("Distancia borde* (mm)")}{" "}</th><th>{" "}{tr("Cortes con cambios")}{" "}</th></tr></thead><tbody>{result.comparison.map((r,i)=><tr key={i} onClick={()=>setPreviewIndex(i)} className="cursor-pointer hover:bg-zinc-800"><td className="py-2">{r.name}</td><td>{r.volumeBefore.toFixed(3)} → {r.volumeAfter.toFixed(3)}</td><td>{r.dice.toFixed(5)}</td><td>{Number.isFinite(r.maxBoundaryDistanceMm)?r.maxBoundaryDistanceMm.toFixed(3):tr("Contorno eliminado")}</td><td>{r.changedSlices.join(', ') || tr("Ninguno")}</td></tr>)}</tbody></table><p className="text-[11px] text-zinc-500">{" "}{tr("*Máxima distancia simétrica entre centros de vóxeles de borde, por corte. Pulse una fila para comparar.")}{" "}</p>{eligible[previewIndex] && result.reconstructed[previewIndex] && <DifferencePreview series={series} original={eligible[previewIndex]} restored={result.reconstructed[previewIndex]}/>}{changed && <label className="block text-sm text-amber-300"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{" "}{tr("He revisado los contornos modificados o eliminados por los filtros.")}{" "}</label>}<button id="btn-confirm-export-monaco" className="bg-blue-700 rounded px-4 py-2 disabled:opacity-40" disabled={busy || (changed && !accepted) || !result.summary.totalContoursCount || (mode!=='rtstruct' && !catalog)} onClick={()=>void download()}>{" "}{tr(mode==='rtstruct'?'Descargar RTSTRUCT TPS (.dcm)':'Descargar DICOM .zip')}{" "}</button></>}
  </section></div>;
}
