import {importSpatialRegistration} from '../utils/spatialRegistrationImporter';
import {RegistrationHistory,registrationSnapshot} from '../utils/registrationHistory';
import {tr} from '../i18n';
import React,{useEffect,useRef,useState} from 'react';
import type {ImageStudy,RegistrationState,RegistrationTransform,DicomSlice} from '../types';
import {libraryIndex,loadSecondaryStudy,LibraryStudy} from '../utils/libraryClient';
import {identity3d,volumeCenter,fitLandmarks,LandmarkPair,Vec3} from '../utils/rigid3d';
import {secondaryDisplay} from '../utils/fusionDisplay';
import {RegistrationTriplanar} from './RegistrationTriplanar';
import {physicalVoi} from '../utils/registrationGeometry';
import {applyRelated,linkedRelations,relatedInitial,RelationPolicy} from '../utils/registrationRelations';
import type {LibraryGroup} from '../utils/libraryClient';
import {compute} from '../utils/computeClient';

interface Props{onSaveGroup?:()=>void;isOpen:boolean;onClose:()=>void;studies:ImageStudy[];registrationState:RegistrationState;onUpdateRegistrationState:(fn:(p:RegistrationState)=>RegistrationState)=>void;onStudyLoaded?:(s:ImageStudy)=>void;currentSliceIndex:number;currentSlice:DicomSlice|null;activeRoiName?:string;onFitVoiToCurrentSlice:()=>void;}
export function RegistrationModal({studies,registrationState:r,onUpdateRegistrationState:update,onStudyLoaded,onClose,onSaveGroup,currentSliceIndex}:Props){
  const ref=studies.find(s=>s.id===r.referenceStudyId) || studies[0],sec=studies.find(s=>s.id===r.secondaryStudyId);
  const history=useRef(new RegistrationHistory()),current=useRef(r),initial=useRef(registrationSnapshot(r));current.current=r;
  const [,refreshHistory]=useState(0),[compareInitial,setCompareInitial]=useState(false);
  const commit=(next:RegistrationState)=>{history.current.commit(current.current,next);current.current=next;update(()=>next);refreshHistory(v=>v+1);};
  const endGesture=()=>{history.current.end(current.current);refreshHistory(v=>v+1);};
  const [relationsReady,setRelationsReady]=useState(false);
  const [groups,setGroups]=useState<LibraryGroup[]>([]),[policy,setPolicy]=useState<RelationPolicy>(r.relationPolicies?.[r.secondaryStudyId] || 'preserve'),[live,setLive]=useState<RegistrationTransform|null>(null),[metric,setMetric]=useState<'nmi_linear'|'nmi'|'ncc'>('nmi_linear');
  const [entries,setEntries]=useState<LibraryStudy[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),[tab,setTab]=useState('manual');
  const [pairs,setPairs]=useState<LandmarkPair[]>([]),[fixed,setFixed]=useState<Vec3|null>(null),[moving,setMoving]=useState<Vec3|null>(null),[proposal,setProposal]=useState<any>(null),abort=useRef<AbortController|null>(null);
  useEffect(()=>{libraryIndex().then(i=>{const patient=i.patients.find(p=>p.id===ref?.patientId);setEntries(patient?.studies || []);setGroups(patient?.groups || []);setRelationsReady(true);}).catch(e=>setError(e.message));return()=>abort.current?.abort();},[]);
  useEffect(()=>{if(!ref)return;const v=r.voi,s=ref.slices[0];if(!v.enabled)update(p=>({...p,voi:{enabled:false,minX:0,maxX:s.cols-1,minY:0,maxY:s.rows-1,minSlice:0,maxSlice:ref.slices.length-1}}));},[ref?.id]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(busy || !(e.ctrlKey||e.metaKey) || !['z','y'].includes(e.key.toLowerCase()) || /INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName))return;e.preventDefault();e.stopPropagation();const next=e.key.toLowerCase()==='y'||e.shiftKey?history.current.redo(current.current):history.current.undo(current.current);current.current=next;update(()=>next);setProposal(null);refreshHistory(v=>v+1);};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true);},[busy,update]);
  if(!ref)return null;
  const nodes=[...entries.map(e=>({...e,frameOfReferenceUID:e.frameOfReferenceUID || studies.find(s=>s.id===e.id)?.frameOfReferenceUID})),...studies.filter(s=>!entries.some(e=>e.id===s.id))];
  const relatives=sec?linkedRelations(nodes,groups,sec.id,ref.id,r.detachedSeriesIds,policy):null;
  const t=r.transforms[sec?.id || '']?.model==='rigid3d'?r.transforms[sec!.id]:identity3d(sec?volumeCenter(sec):[0,0,0]);
  const apply=(value:RegistrationTransform)=>{if(!sec)return;try{if(!relationsReady && policy!=='single')throw new Error('Espere a cargar las relaciones de la biblioteca.');const next=applyRelated(r,nodes,groups,sec.id,value,policy);setError('');setProposal(null);commit(next);}catch(e){setError((e as Error).message);}};
  const choose=async(id:string)=>{setBusy(true);setError('');setProposal(null);setLive(null);setPolicy(r.relationPolicies?.[id] || 'preserve');setPairs([]);setFixed(null);setMoving(null);try{let s=studies.find(s=>s.id===id);if(!s){const entry=entries.find(e=>e.id===id)!;s=await loadSecondaryStudy(entry.key);onStudyLoaded?.(s);}update(p=>({...p,secondaryStudyId:id,active:true,...secondaryDisplay(s!),transforms:{...p.transforms,[id]:relatedInitial(p,[...nodes.filter(n=>n.id!==id),{...s!,key:entries.find(e=>e.id===id)?.key}],groups,id)}}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const runAuto=async()=>{if(!sec)return;setBusy(true);setError('');setProposal(null);setLive(null);abort.current=new AbortController();try{const result=await compute('registration',[ref,sec,t,{metric,voi:physicalVoi(ref,r.voi)}],{signal:abort.current.signal,progress:p=>{setProgress(`${p.percent}% · ${Number(p.score).toFixed(4)}`);if(p.transform)setLive(p.transform);}});setProposal(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);setProgress('');setLive(null);}};
  const button='rounded border border-zinc-600 px-3 py-1.5 hover:bg-zinc-800 disabled:opacity-40';
  return <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-3"><section className="bg-zinc-950 text-zinc-200 border border-zinc-600 rounded-xl w-full max-w-[1500px] max-h-[95vh] overflow-auto p-4 space-y-3">
    <header className="flex justify-between"><div><h2 className="font-semibold">{" "}{tr("Corregistro rígido 3D")}{" "}</h2><p className="text-xs text-zinc-400">{" "}{tr("Referencia:")}{" "}{ref.seriesDescription}{" "}{tr("· Coordenadas físicas DICOM · Sin escalamiento")}{" "}</p></div><button className={button} disabled={busy} onClick={onClose}>{" "}{tr("Cerrar")}{" "}</button></header>
    <label className="block text-xs">{" "}{tr("Imagen secundaria")}{" "}<select aria-label={tr("Imagen secundaria")} className="bg-zinc-800 p-2 ml-2" disabled={busy} value={sec?.id===ref.id?'':sec?.id || ''} onChange={e=>void choose(e.target.value)}><option value="" disabled>{" "}{tr("Seleccione una serie")}{" "}</option>{[...entries.filter(e=>e.id!==ref.id).map(e=>({id:e.id,name:e.description})),...studies.filter(s=>s.id!==ref.id && !entries.some(e=>e.id===s.id)).map(s=>({id:s.id,name:s.seriesDescription}))].map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
    <div className="flex gap-2">{[["manual",tr("Manual")],["points",tr("Puntos anatómicos")],["auto",tr("Automático local")]].map(([id,label])=><button key={id} disabled={busy} className={button+(tab===id?' bg-blue-950':'')} onClick={()=>setTab(id)}>{label}</button>)}</div>
    <div className="flex gap-2 text-xs"><button className={button} disabled={busy || !history.current.past.length} onClick={()=>{const next=history.current.undo(r);current.current=next;update(()=>next);setProposal(null);refreshHistory(v=>v+1);}}>{tr('Deshacer corregistro')}</button><button className={button} disabled={busy || !history.current.future.length} onClick={()=>{const next=history.current.redo(r);current.current=next;update(()=>next);setProposal(null);refreshHistory(v=>v+1);}}>{tr('Rehacer corregistro')}</button><button className={button} aria-pressed={compareInitial} onClick={()=>setCompareInitial(v=>!v)}>{tr('Comparar con inicial')}</button><button className={button} disabled={busy || !sec || t.locked} onClick={()=>apply(initial.current.transforms[sec!.id] || identity3d(volumeCenter(sec!)))}>{tr('Restaurar transformación inicial')}</button></div>
    <label className="text-xs">{tr('Importar DICOM REG')} <input type="file" accept=".dcm,.reg" disabled={busy || !sec || sec.id===ref.id} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file || !sec)return;try{if(file.size>16*1024*1024)throw new Error('REG exceeds 16 MiB');setProposal(importSpatialRegistration(new Uint8Array(await file.arrayBuffer()),ref,sec));setCompareInitial(false);setError('');}catch(e){setError((e as Error).message);}}}/></label>
    {error && <p role="alert" className="text-red-300">{" "}{tr(error)}{" "}</p>}
    {sec && sec.id!==ref.id && <>
      <details className="text-xs border border-zinc-700 rounded p-2" open={!!error}><summary>{tr('Relaciones y conflictos de corregistro')} · {Object.keys(relatives?.toSelected || {}).length} {tr('series vinculadas')}</summary><p>{tr('Se conservan las relaciones espaciales DICOM y los grupos guardados. Una referencia fija o una serie bloqueada no se desplaza sin resolver el conflicto.')}</p><ul className="list-disc pl-4">{Object.keys(relatives?.toSelected || {}).map(id=><li key={id}>{(()=>{const n=nodes.find(n=>n.id===id);return n && ('description' in n?n.description:n.seriesDescription);})()} · {id===ref.id?tr('Referencia fija'):r.transforms[id]?.locked?tr('Bloqueada'):tr('Se moverá con la seleccionada')} · {relatives?.paths[id]?.map(key=>{const n=nodes.find(n=>n.id===key);return n && ('description' in n?n.description:n.seriesDescription);}).join(' → ')} · {relatives?.sources[id]?.join(' → ')}</li>)}</ul>{relatives?.conflicts.map((conflict,i)=><p key={i} className="text-amber-300">{conflict}</p>)}<label>{tr('Política de resolución')} <select aria-label={tr('Política de resolución')} disabled={busy} value={policy} className="bg-zinc-800 p-1" onChange={e=>{setPolicy(e.target.value as RelationPolicy);setError('');}}><option value="preserve">{tr('Preservar relaciones; detener ante conflictos')}</option><option value="dicom">{tr('Priorizar relaciones DICOM')}</option><option value="saved">{tr('Priorizar grupos guardados')}</option><option value="single">{tr('Solo seleccionada: desvincular')}</option></select></label><p>{Object.keys(relatives?.toSelected || {}).map(id=>nodes.find(n=>n.id===id)).map(n=>n && ('description' in n?n.description:n.seriesDescription)).join(' · ')}</p>{r.detachedSeriesIds?.includes(sec.id) && <button disabled={busy} className={button} onClick={()=>{commit({...r,detachedSeriesIds:r.detachedSeriesIds?.filter(id=>id!==sec.id),relationPolicies:{...r.relationPolicies,[sec.id]:'preserve'}});setPolicy('preserve');}}>{tr('Restablecer vínculo')}</button>}</details>
      {tab==='manual' && <><p className="text-xs text-zinc-400">{tr('Traslade o rote desde cualquiera de los tres planos. Las tres vistas comparten la misma transformación física.')}</p><div className="grid grid-cols-3 lg:grid-cols-6 gap-2">{[["translationX",tr("Traslación X (mm)")],["translationY",tr("Traslación Y (mm)")],["translationZ",tr("Traslación Z (mm)")],["rotationX",tr("Rotación X (°)")],["rotationY",tr("Rotación Y (°)")],["rotationDeg",tr("Rotación Z (°)")]].map(([key,label])=><label key={key} className="text-xs">{label}<input aria-label={label} disabled={busy || t.locked} type="number" step="0.1" onFocus={()=>history.current.begin(current.current)} onBlur={endGesture} value={Number((t[key] || 0).toFixed(3))} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value))apply({...t,[key]:value});}} className="block bg-zinc-800 w-full p-2 mt-1"/></label>)}</div><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>apply({...t,locked:!t.locked})}>{t.locked?tr("Desbloquear"):tr("Bloquear transformación")}</button><button className={button} disabled={busy || t.locked} onClick={()=>apply(identity3d(volumeCenter(sec)))}>{" "}{tr("Identidad DICOM")}{" "}</button><button className={button} disabled={busy || t.locked} onClick={()=>{const a=volumeCenter(ref),b=volumeCenter(sec);apply({...identity3d(b),translationX:a[0]-b[0],translationY:a[1]-b[1],translationZ:a[2]-b[2]});}}>{" "}{tr("Alinear centros")}{" "}</button></div></>}
      {tab==='points' && <><p className="text-xs text-zinc-400">{" "}{tr("Seleccione la misma referencia anatómica en ambas imágenes y añada el par. Use al menos tres puntos no alineados, distribuidos en el volumen.")}{" "}</p><div className="flex gap-3"><div className="w-1/2"><p>{tr("Referencia")}</p><RegistrationTriplanar reference={ref} secondary={ref} transform={identity3d()} display={{...r,fusionOpacity:0,voi:{...r.voi,enabled:false}}} busy={false} onVoi={()=>{}} initialZ={currentSliceIndex} onPoint={setFixed}/></div><div className="w-1/2"><p>{tr("Secundaria")}</p><RegistrationTriplanar key={sec.id} reference={sec} secondary={sec} transform={identity3d()} display={{...r,fusionOpacity:0,voi:{...r.voi,enabled:false}}} busy={false} onVoi={()=>{}} initialZ={Math.floor(sec.slices.length/2)} onPoint={setMoving}/></div></div><p className="text-xs">{" "}{tr("Referencia:")}{" "}{fixed?.map(v=>v.toFixed(2)).join(', ') || tr("pendiente")}{" "}{tr("· Secundaria:")}{" "}{moving?.map(v=>v.toFixed(2)).join(', ') || tr("pendiente")}{" "}{tr("mm")}{" "}</p><button className={button} disabled={!fixed || !moving || busy} onClick={()=>{setPairs([...pairs,{fixed:fixed!,moving:moving!}]);setFixed(null);setMoving(null);setProposal(null);}}>{" "}{tr("Añadir par")}{" "}</button>{pairs.map((p,i)=><div key={i} className="text-xs flex gap-3"><span>{" "}{tr("Par")}{" "}{i+1}: {p.fixed.map(v=>v.toFixed(1)).join(', ')} ↔ {p.moving.map(v=>v.toFixed(1)).join(', ')}{" "}{tr("mm")}{" "}{proposal?.errors && tr("· error {0} mm", [proposal.errors[i].toFixed(2)])}</span><button onClick={()=>{setPairs(pairs.filter((_,j)=>j!==i));setProposal(null);}}>{" "}{tr("Quitar")}{" "}</button></div>)}<button className={button} disabled={pairs.length<3 || t.locked} onClick={()=>{try{setError('');setProposal(fitLandmarks(pairs));}catch(e){setError((e as Error).message);}}}>{" "}{tr("Calcular por puntos")}{" "}</button></>}
      {tab==='auto' && <><label className="text-xs">{tr('Métrica automática')} <select aria-label={tr('Métrica automática')} className="bg-zinc-800 p-1" disabled={busy} value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="nmi_linear">{tr('Información mutua suave (TC–RM / TC–TC)')}</option><option value="ncc">{tr('Correlación (TC–TC)')}</option><option value="nmi">{tr('Información mutua clásica')}</option></select></label><p className="text-xs text-zinc-400">{" "}{tr("Registro rígido local de seis parámetros, con refinamiento de pasos gruesos a finos. Utiliza el VOI cuando está habilitado. Las actualizaciones son una vista previa; revise la anatomía antes de aceptar la propuesta.")}{" "}</p><button className={button} disabled={busy || t.locked} onClick={()=>void runAuto()}>{" "}{tr("Calcular registro automático 3D")}{" "}</button>{busy && <button className={button} onClick={()=>abort.current?.abort()}>{" "}{tr("Cancelar cálculo")}{" "}</button>}<p role="status">{" "}{tr(progress)}{" "}</p></>}
      {proposal && <div className="border border-blue-700 p-3 rounded"><p>{proposal.source?proposal.source:proposal.rms!==undefined?tr("Error RMS de puntos: {0} mm", [proposal.rms.toFixed(2)]):tr("Puntuación: {0}", [Number(proposal.score || 0).toFixed(4)])}{" "}{tr("· Propuesta pendiente")}{" "}</p>{proposal.quality && <div className="text-xs space-y-1"><p>{tr('Cobertura inicial/final')}: {(proposal.quality.initialCoverage*100).toFixed(1)}% → {(proposal.quality.finalCoverage*100).toFixed(1)}%</p><p>{tr('Métrica inicial/final')}: {proposal.quality.initialScore?.toFixed(4) || '—'} → {proposal.quality.finalScore.toFixed(4)}</p><p>{tr('Cambio desde inicial')}: {proposal.quality.displacementMm.toFixed(2)} mm · {proposal.quality.rotationChangeDeg.toFixed(2)}°</p>{proposal.quality.warnings.map((w:string)=><p className="text-amber-300" key={w}>{tr(w)}</p>)}<p>{tr('La métrica y la cobertura no certifican exactitud anatómica.')}</p></div>}<button className={button} disabled={busy || t.locked} onClick={()=>apply(proposal.transform)}>{" "}{tr("Aceptar transformación")}{" "}</button><button className={button} onClick={()=>setProposal(null)}>{" "}{tr("Descartar propuesta")}{" "}</button></div>}
      {(tab!=='points' || proposal) && <RegistrationTriplanar key={ref.id} reference={ref} secondary={sec} transform={compareInitial?(initial.current.transforms[sec.id] || identity3d(volumeCenter(sec))):live || proposal?.transform || t} display={r} initialZ={currentSliceIndex} busy={busy} onVoi={voi=>{setProposal(null);update(p=>({...p,voi}));}} onGestureStart={()=>history.current.begin(current.current)} onGestureEnd={endGesture} onTransform={tab==='manual' && !busy && !t.locked && !proposal && !compareInitial?apply:undefined}/>}
      <div className="flex flex-wrap gap-3 items-center text-xs"><label><input type="checkbox" checked={r.active} onChange={e=>update(p=>({...p,active:e.target.checked,transforms:{...p.transforms,[sec.id]:t}}))}/>{" "}{tr("Mostrar fusión en visor")}{" "}</label><label>{" "}{tr("Modo")}{" "}<select className="bg-zinc-800 p-1" value={r.fusionMode} onChange={e=>update(p=>({...p,fusionMode:e.target.value as any}))}><option value="blend">{" "}{tr("Mezcla")}{" "}</option><option value="checkerboard">{" "}{tr("Damero")}{" "}</option><option value="split_horizontal">{" "}{tr("Cortina")}{" "}</option><option value="split_vertical">{tr("División superior/inferior")}</option><option value="difference">{" "}{tr("Diferencia")}{" "}</option></select></label><label>{tr('Paleta secundaria')} <select aria-label={tr('Paleta secundaria')} className="bg-zinc-800" value={r.secondaryColorMap} onChange={e=>update(p=>({...p,secondaryColorMap:e.target.value as RegistrationState['secondaryColorMap']}))}>{['grayscale','cyan','hot_iron','rainbow'].map(c=><option key={c} value={c}>{c}</option>)}</select></label><button className={button} onClick={()=>update(p=>({...p,...secondaryDisplay(sec)}))}>{tr('Restablecer ventana secundaria')}</button><label>{tr('Posición de cortina')}<input aria-label={tr('Posición de cortina')} type="range" min="0" max="1" step=".01" value={r.splitPosition} onChange={e=>update(p=>({...p,splitPosition:Number(e.target.value)}))}/></label><label>{" "}{tr("Centro secundario")}{" "}<input aria-label={tr("Centro de ventana secundaria")} type="number" className="bg-zinc-800 w-20" value={r.secondaryWindowCenter} onChange={e=>update(p=>({...p,secondaryWindowCenter:Number(e.target.value)}))}/></label><label>{" "}{tr("Ancho secundario")}{" "}<input aria-label={tr("Ancho de ventana secundaria")} type="number" min="1" className="bg-zinc-800 w-20" value={r.secondaryWindowWidth} onChange={e=>update(p=>({...p,secondaryWindowWidth:Math.max(1,Number(e.target.value))}))}/></label><label>{" "}{tr("Opacidad")}{" "}<input type="range" min="0" max="1" step="0.05" value={r.fusionOpacity} onChange={e=>update(p=>({...p,fusionOpacity:Number(e.target.value)}))}/></label><button className={button} disabled={busy} onClick={onSaveGroup}>{" "}{tr("Guardar grupo en biblioteca")}{" "}</button></div>
    </>}
  </section></div>;
}

