import {maskScale,maskSeries} from '../utils/segmentationGrid';
import {tr} from '../i18n';
import React,{useState,useEffect,useRef} from 'react';
import type {DicomSeries,StructureRoi,RoiType} from '../types';
import {getPreferences,savePreferences} from '../utils/libraryClient';
import {DifferencePreview} from './MonacoExportModal';
import {compute} from '../utils/computeClient';
const packs:Record<string,string[]>={Pelvis:['BODY','GTV','CTV','PTV','Bladder','Rectum','Femur_Head_L','Femur_Head_R'],Tórax:['BODY','GTV','CTV','PTV','Lung_L','Lung_R','Heart','Esophagus','SpinalCord'],Cabeza:['BODY','GTV','CTV','PTV','Brain','Brainstem','OpticNrv_L','OpticNrv_R','OpticChiasm']};
const normalized=(name:string)=>name.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_\-]/g,'_').replace(/_+/g,'_').slice(0,64);
export function WorkflowTools({series,rois,active,z,onChange,onJump}:{series:DicomSeries|null;rois:StructureRoi[];active:StructureRoi|null;z:number;onChange:(r:StructureRoi[])=>void;onJump:(z:number)=>void}){
  const [section,setSection]=useState('');
  const latest=useRef({series,rois});latest.current={series,rois};
  useEffect(()=>{const open=(e:Event)=>setSection((e as CustomEvent).detail);window.addEventListener('roi-workflow',open);return()=>window.removeEventListener('roi-workflow',open);},[]);
  const [pack,setPack]=useState('Pelvis'),[templates,setTemplates]=useState<Record<string,string[]>>(packs),[names,setNames]=useState(packs.Pelvis.join('\n')),[name,setName]=useState(''),[start,setStart]=useState(1),[end,setEnd]=useState(1),[mode,setMode]=useState('preserve'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<StructureRoi[]|null>(null),[previewId,setPreviewId]=useState(''),[prefs,setPrefs]=useState<any>({}),file=useRef<HTMLInputElement>(null);
  useEffect(()=>{getPreferences().then(p=>{setPrefs(p);if(p.templates)setTemplates({...packs,...p.templates});}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{setName(active?.name || '');setPreview(null);},[active?.id]);
  useEffect(()=>{setPreview(null);},[rois,series]);
  const act=(fn:()=>void)=>{try{setError('');fn();}catch(e){setError((e as Error).message);}};
  const copyPreview=()=>act(()=>{if(!series || !active || active.locked)throw new Error('Seleccione una estructura editable.');const source=active.sliceMasks[z];if(!source?.some(v=>v))throw new Error('El corte actual no tiene contorno.');if(!Number.isInteger(start) || !Number.isInteger(end) || start<1 || end<start || end>series.slices.length)throw new Error('Rango de cortes inválido.');
    const masks={...active.sliceMasks};for(let i=start-1;i<end;i++){if(i===z)continue;const previous=masks[i];if(mode==='preserve' && previous?.some(v=>v))continue;if(mode==='union' && previous)masks[i]=Uint8Array.from(source,(v,k)=>v || previous[k]);else masks[i]=source;}setPreview(rois.map(r=>r.id===active.id?{...r,sliceMasks:masks}:r));});
  const importFile=async(f:File)=>{if(!series)return;setBusy(true);setError('');try{const imported=await compute<StructureRoi[]>('importRT',[new Uint8Array(await f.arrayBuffer()),series,2]);const used=new Set(rois.map(r=>r.name.toLowerCase()));for(const r of imported){const base=r.name;let n=1;while(used.has(r.name.toLowerCase()))r.name=base+'_import'+n++;used.add(r.name.toLowerCase());}setPreview([...rois,...imported]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const button='border border-zinc-600 rounded px-2 py-1 hover:bg-zinc-800 disabled:opacity-40';
  return <div className="text-xs">{active && series && <div className="flex items-center gap-2 mb-2" title={tr('2× duplica la resolución X/Y de la máscara, mantiene los cortes originales y no añade detalle anatómico.')}><label>{tr('Resolución de máscara')}: <select aria-label={tr('Resolución de máscara')} disabled={busy||active.locked||Object.values(active.sliceMasks).some(m=>m.some(Boolean))} value={maskScale(active)} className="bg-zinc-800" onChange={e=>onChange(rois.map(r=>r.id===active.id?{...r,maskScale:Number(e.target.value) as 1|2,sliceMasks:{},volumeCm3:undefined}:r))}><option value="1">1× XY</option><option value="2">2× XY</option></select></label>{maskScale(active)===1 && <button className={button} disabled={busy||active.locked} onClick={async()=>{setBusy(true);try{const upgraded=await compute<StructureRoi>('upgradeMask',[active,maskSeries(series,1)]);if(latest.current.series!==series||latest.current.rois!==rois)throw new Error('La estructura cambió durante el cálculo. Intente nuevamente.');onChange(rois.map(r=>r.id===active.id?upgraded:r));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{tr('Aumentar a 2×')}</button>}</div>}{error&&!section&&<p role="alert">{tr(error)}</p>}<div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setSection('templates')}>{" "}{tr("Plantillas")}{" "}</button><button className={button} disabled={!series} onClick={()=>setSection('import')}>{" "}{tr("Importar RTSTRUCT")}{" "}</button></div>{section && <div className="fixed inset-0 z-[80] bg-black/70 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label={tr("Acciones de estructuras")} className="bg-zinc-950 border border-zinc-600 rounded-lg p-4 w-full max-w-xl max-h-[90vh] overflow-auto space-y-3"><header className="flex justify-between items-center"><h2 className="text-sm font-semibold">{({templates:tr("Plantillas"),copy:tr("Copiar contorno"),import:tr("Importar RTSTRUCT"),rename:tr("Renombrar estructura")})[section]}</h2><button className={button} disabled={busy} onClick={()=>{setSection('');setPreview(null);}}>{" "}{tr("Cerrar")}{" "}</button></header>
    {error && <p role="alert" className="text-red-300">{" "}{tr(error)}{" "}</p>}
    {section==='templates' && <><label>{" "}{tr("Plantilla")}{" "}<select className="bg-zinc-800 p-1" value={pack} onChange={e=>{setPack(e.target.value);setNames(templates[e.target.value].join('\n'));}}>{Object.keys(templates).map(p=><option key={p} value={p}>{tr(p)}</option>)}</select></label>
    <p className="text-zinc-400">{" "}{tr("Una ROI por línea: nombre | tipo (GTV, CTV, PTV, OAR, EXTERNAL, PRV, SUPPORT, AVOIDANCE) | color #RRGGBB. Tipo y color son opcionales.")}{" "}</p><textarea aria-label={tr("Estructuras de la plantilla")} className="w-full bg-zinc-900 border border-zinc-700 p-1" rows={3} value={names} onChange={e=>setNames(e.target.value)}/>
    <div className="flex gap-2"><button className={button} disabled={!series} onClick={()=>act(()=>{const used=new Set(rois.map(r=>r.name.toLowerCase())),added:StructureRoi[]=[];for(const raw of names.split('\n')){const [rawName,rawType,rawColor]=raw.split('|').map(v=>v.trim());const name=normalized(rawName);if(!name || used.has(name.toLowerCase()))continue;used.add(name.toLowerCase());const type:RoiType=rawType?rawType as RoiType:name==='BODY'?'EXTERNAL':['GTV','CTV','PTV'].includes(name)?name as RoiType:'OAR';if(!['EXTERNAL','GTV','CTV','PTV','OAR','PRV','SUPPORT','AVOIDANCE'].includes(type))throw new Error('Tipo de ROI inválido: '+type);if(rawColor && !/^#[0-9a-f]{6}$/i.test(rawColor))throw new Error('Color inválido: '+rawColor);added.push({id:crypto.randomUUID(),name,type,color:rawColor || (type==='PTV'?'#ef4444':type==='EXTERNAL'?'#38bdf8':'#22c55e'),visible:true,locked:false,opacity:.4,maskScale:2,sliceMasks:{}});}onChange([...rois,...added]);})}>{" "}{tr("Añadir estructuras")}{" "}</button><button className={button} onClick={async()=>{try{const next={...prefs,templates:{...templates,[pack]:names.split('\n').map(v=>v.trim()).filter(Boolean)}};await savePreferences(next);setPrefs(next);setTemplates(next.templates);}catch(e){setError((e as Error).message);}}}>{" "}{tr("Guardar plantilla local")}{" "}</button></div>
    </>}
    {section==='rename' && <><label>{" "}{tr("Nombre de ROI activa")}{" "}<input aria-label={tr("Nombre de ROI activa")} list="roi-names" className="w-full bg-zinc-900 p-1" value={name} onChange={e=>setName(e.target.value)}/></label><datalist id="roi-names">{Array.from(new Set(Object.values(templates).flat())).map(n=><option key={n} value={String(n).split('|')[0].trim()}/>)}</datalist><button className={button} disabled={!active || active.locked} onClick={()=>act(()=>{const clean=normalized(name);if(!clean)throw new Error('Nombre vacío.');if(rois.some(r=>r.id!==active!.id && r.name.toLowerCase()===clean.toLowerCase()))throw new Error('Ya existe esa estructura.');onChange(rois.map(r=>r.id===active!.id?{...r,name:clean}:r));setName(clean);})}>{" "}{tr("Normalizar y renombrar")}{" "}</button>
    </>}
    {section==='copy' && <div className="border-t border-zinc-700 pt-2">{" "}{tr("Copiar corte actual")}{" "}{z+1} → <button className={button} onClick={()=>{setStart(z+2);setEnd(z+2);}}>{" "}{tr("Siguiente")}{" "}</button><button className={button} onClick={()=>{setStart(z);setEnd(z);}}>{" "}{tr("Anterior")}{" "}</button><div className="flex gap-1 mt-1"><input aria-label={tr("Copia desde corte")} type="number" min="1" max={series?.slices.length} value={start} onChange={e=>setStart(Number(e.target.value))} className="w-16 bg-zinc-800"/><span>{" "}{tr("a")}{" "}</span><input aria-label={tr("Copia hasta corte")} type="number" min="1" max={series?.slices.length} value={end} onChange={e=>setEnd(Number(e.target.value))} className="w-16 bg-zinc-800"/><select aria-label={tr("Modo de copia")} className="bg-zinc-800" value={mode} onChange={e=>setMode(e.target.value)}><option value="preserve">{" "}{tr("Conservar existentes")}{" "}</option><option value="union">{" "}{tr("Sumar")}{" "}</option><option value="replace">{" "}{tr("Reemplazar")}{" "}</option></select></div><button className={button} disabled={!active || active.locked} onClick={copyPreview}>{" "}{tr("Preparar copia")}{" "}</button></div>}
    {section==='import' && <><input ref={file} type="file" accept=".dcm" className="hidden" onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value='';}}/><button className={button} disabled={busy || !series} onClick={()=>file.current?.click()}>{busy?tr("Leyendo RTSTRUCT…"):tr("Importar RTSTRUCT del TPS")}</button></>}
    {preview && <div className="bg-blue-950 p-2 rounded"><p>{" "}{tr("Propuesta:")}{" "}{preview.length}{" "}{tr("ROI,")}{" "}{preview.reduce((n,r)=>n+Object.keys(r.sliceMasks).length,0)}{" "}{tr("máscaras por corte. Se conserva el original hasta aceptar.")}{" "}</p>{series && <><select aria-label={tr("ROI de la propuesta")} className="bg-zinc-800" value={previewId || preview.find(r=>r.id===active?.id)?.id || preview[0]?.id} onChange={e=>setPreviewId(e.target.value)}>{preview.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{(()=>{const after=preview.find(r=>r.id===(previewId || active?.id)) || preview[0];return after?<DifferencePreview series={series} original={rois.find(r=>r.id===after.id) || {...after,sliceMasks:{}}} restored={after}/>:null;})()}</>}<button className={button} onClick={()=>{onChange(preview);setPreview(null);setSection('');}}>{" "}{tr("Aceptar cambios")}{" "}</button><button className={button} onClick={()=>setPreview(null)}>{" "}{tr("Cancelar")}{" "}</button></div>}
    {active && <button className={button} onClick={()=>{const first=Object.keys(active.sliceMasks).map(Number).sort((a,b)=>a-b).find(k=>active.sliceMasks[k].some(v=>v));if(first!==undefined)onJump(first);}}>{" "}{tr("Ir al primer contorno de la ROI")}{" "}</button>}
  </section></div>}</div>;
}
