import {createRequire} from 'node:module';import express from 'express';import {promises as fs} from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {libraryRouter,createLibrary} from '../server/library.mjs';import {applicationLifecycle} from '../server/application.mjs';import {sessionRecords} from '../src/utils/sessionStream';import {defaultRegistration} from '../src/utils/libraryClient';
const require=createRequire(import.meta.url),{chromium}=require(process.env.IVCS_PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,channel:process.platform==='win32'?'msedge':undefined});
try{for(const choice of ['save','discard']){
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'ivcs-exit-browser-')),app=express();let server:any,shutdowns=0;
 const lifecycle=applicationLifecycle(()=>new Promise<void>(resolve=>{shutdowns++;server.close(resolve);}));app.use('/api/application',lifecycle.router);app.use(lifecycle.gate);app.use('/api/library',libraryRouter(root));app.use(express.static(path.resolve('dist')));app.get('*',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const url='http://127.0.0.1:'+server.address().port;
 const study:any={id:'ref',patientId:'SYNTHETIC-EXIT',patientName:'Synthetic^Exit',modality:'CT',studyDescription:'QA',seriesDescription:'QA',slices:Array.from({length:3},(_,z)=>({id:'z'+z,sliceIndex:z,rows:64,cols:64,huData:new Int16Array(4096),pixelSpacing:[1,1],sliceThickness:2,sliceLocation:2*z,imagePositionPatient:[0,0,2*z],imageOrientationPatient:[1,0,0,0,1,0],minHU:0,maxHU:0,windowCenter:40,windowWidth:400,rescaleSlope:1,rescaleIntercept:0}))};
 const roi:any={id:'r',name:'QA',type:'OAR',color:'#ff0000',visible:true,locked:false,opacity:.3,maskScale:2,sliceMasks:{}},session:any={format:'radcontour-session',version:1,series:study,studies:[study],rois:[roi],activeRoiId:'r',currentSliceIndex:1,windowCenter:40,windowWidth:400,registrationState:defaultRegistration('ref')};const file=path.join(root,'fixture.ivcs');await fs.writeFile(file,[...sessionRecords(session)].join(''));
 const context=await browser.newContext(),page=await context.newPage();await page.addInitScript({content:'window.close=()=>{};'});await page.goto(url);await page.locator('input[accept=".json,.ivcs"]').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('header')?.textContent?.includes('SYNTHETIC-EXIT'));const canvas=page.getByTestId('axial-canvas');await page.getByLabel('Contour mode',{exact:true}).selectOption('open');const b=(await canvas.boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+20,b.y+b.height/2,{steps:5});await page.mouse.up();await page.getByText('Unsaved changes',{exact:true}).waitFor();
 const nativeDialog=new Promise<void>(resolve=>page.once('dialog',async d=>{assert.equal(d.type(),'beforeunload');await d.dismiss();resolve();}));await page.close({runBeforeUnload:true});await nativeDialog;assert.equal(page.isClosed(),false);await page.getByRole('dialog',{name:'Close IVCS RT'}).waitFor();assert.equal(shutdowns,0);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 const other=await context.newPage();await other.goto(url+'/library');await other.waitForLoadState('networkidle');await page.locator('#btn-exit-application').click();await page.getByTestId('exit-discard').click();await page.getByRole('alert').filter({hasText:'Close the other IVCS RT windows'}).waitFor();assert.equal(shutdowns,0);await other.close();
 if(choice==='save'){
  await page.route('**/api/library/session',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Synthetic save failure'})}));await page.getByTestId('exit-save').click();await page.getByRole('alert').filter({hasText:'Synthetic save failure'}).waitFor();assert.equal(shutdowns,0);assert.equal((await fetch(url+'/api/application/status')).ok,true);await page.unroute('**/api/library/session');
 }
 await page.getByTestId('exit-'+choice).click();await page.getByText('Server stopped. You can now close this tab.',{exact:true}).waitFor({timeout:15000});assert.equal(shutdowns,1);
 const library=createLibrary(root),index=await library.list(),saved=await library.open(index.latest),masks=saved.state.rois[0].sliceMasks;assert.equal(Object.keys(masks).length>0,choice==='save');
 const event=await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;});assert.equal(event,false);await context.close();console.log('PASS exit '+choice+': native close warning, cancel, other-window guard, saved data outcome, server stop and fallback page');
}}finally{await browser.close();}
