import {createRequire} from 'node:module';import express from 'express';import {promises as fs} from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {libraryRouter} from '../server/library.mjs';import {sessionRecords} from '../src/utils/sessionStream';import {defaultRegistration} from '../src/utils/libraryClient';
const require=createRequire(import.meta.url),{chromium}=require(process.env.IVCS_PLAYWRIGHT_MODULE||'playwright');
const root=await fs.mkdtemp(path.join(os.tmpdir(),'ivcs-line-')),app=express();app.use('/api/library',libraryRouter(root));app.use(express.static(path.resolve('dist')));app.get('*',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
const browser=await chromium.launch({headless:true,channel:process.platform==='win32'?'msedge':undefined});
try{
 const slice:any={id:'synthetic',sliceIndex:0,rows:128,cols:128,huData:new Int16Array(128*128).fill(-1000),pixelSpacing:[2,1],sliceThickness:3,sliceLocation:0,imagePositionPatient:[0,0,0],imageOrientationPatient:[1,0,0,0,1,0],minHU:-1000,maxHU:-1000,windowCenter:40,windowWidth:400,rescaleSlope:1,rescaleIntercept:0};
 const study:any={id:'ref',patientId:'SYNTHETIC-LINE',patientName:'Synthetic line width',studyDescription:'QA',seriesDescription:'QA',modality:'CT',slices:[slice]},mask=new Uint8Array(256*256);
 for(let y=80;y<176;y++)for(let x=80;x<176;x++)mask[y*256+x]=1;
 const roi:any={id:'r',name:'Synthetic edge',type:'OAR',color:'#ff0000',visible:true,locked:false,opacity:0,maskScale:2,sliceMasks:{0:mask}},session:any={format:'radcontour-session',version:1,series:study,studies:[study],rois:[roi],activeRoiId:roi.id,currentSliceIndex:0,windowCenter:40,windowWidth:400,registrationState:defaultRegistration('ref')};
 const file=path.join(root,'synthetic.ivcs');await fs.writeFile(file,[...sessionRecords(session)].join(''));
 const page=await browser.newPage({viewport:{width:1500,height:1000},deviceScaleFactor:2}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript({content:'window.__name=(fn)=>fn;'});await page.goto('http://127.0.0.1:'+(server.address() as any).port);await page.locator('input[accept=".json,.ivcs"]').setInputFiles(file);const canvas=page.getByTestId('axial-canvas');await canvas.waitFor();await page.waitForTimeout(500);
 let editScale=2;async function widths(){return canvas.evaluate((c:HTMLCanvasElement,scale:number)=>{const zoom=Number(c.dataset.zoom),ctx=c.getContext('2d')!,data=ctx.getImageData(0,0,c.width,c.height).data,left=c.width/2+(40-64)*scale*zoom,top=c.height/2+(40-64)*scale*zoom*2;const count=(horizontal:boolean)=>{let n=0;for(let k=-8;k<=8;k++){const x=horizontal?Math.round(left)+k:Math.round(c.width/2),y=horizontal?Math.round(c.height/2):Math.round(top)+k,i=(y*c.width+x)*4;if(data[i]>120&&data[i+1]<40&&data[i+2]<40)n++;}return n;};return {zoom,vertical:count(true),horizontal:count(false)};},editScale);}
 const measurements:any[]=[];
 for(const width of [1,3]){await page.getByTestId('contour-line-width').selectOption(String(width));await page.waitForTimeout(100);const before=await widths();for(const edge of [before.vertical,before.horizontal])assert.ok(Math.abs(edge-width)<=1&&edge>0,JSON.stringify({width,before}));
 await canvas.hover();await page.keyboard.down('Control');for(let i=0;i<5;i++){await page.mouse.wheel(0,-100);await page.waitForTimeout(30);}await page.keyboard.up('Control');await page.waitForTimeout(150);const after=await widths();assert.ok(after.zoom>before.zoom);for(const edge of [after.vertical,after.horizontal])assert.ok(Math.abs(edge-width)<=1&&edge>0,JSON.stringify({width,after}));measurements.push({width,before,after});await page.getByRole('button',{name:'Reset axial zoom',exact:true}).click();await page.waitForTimeout(100);}
 await page.screenshot({path:'build/contour-lines-20260923.png'});
 await page.reload();await page.waitForFunction(()=>document.querySelector('header')?.textContent?.includes('SYNTHETIC-LINE'));await canvas.waitFor();assert.equal(await page.getByTestId('contour-line-width').inputValue(),'3');const mixedFile=path.join(root,'mixed.ivcs'),legacy={...roi,id:'legacy',name:'Legacy empty',maskScale:1,sliceMasks:{}};const mixedStudy={...study,id:'mixed-reference',patientId:'SYNTHETIC-MIXED'};await fs.writeFile(mixedFile,[...sessionRecords({...session,series:mixedStudy,studies:[mixedStudy],registrationState:defaultRegistration(mixedStudy.id),rois:[roi,legacy],activeRoiId:'legacy'})].join(''));await page.locator('input[accept=".json,.ivcs"]').setInputFiles(mixedFile);await page.waitForFunction(()=>document.querySelector('header')?.textContent?.includes('SYNTHETIC-MIXED'));await canvas.waitFor();await page.waitForTimeout(500);editScale=1;const mixed=await widths();await page.screenshot({path:'build/contour-lines-mixed-20260923.png'});console.log('Mixed grid',mixed);assert.equal(mixed.vertical,3,JSON.stringify(mixed));assert.equal(mixed.horizontal,3,JSON.stringify(mixed));assert.deepEqual(errors,[]);console.log('PASS constant screen line width, anisotropic pixels, transparent fill, zoom, preference persistence',JSON.stringify(measurements));
}finally{await browser.close();server.close();}
