import {createRequire} from 'node:module';import express from 'express';import {promises as fs} from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import JSZip from 'jszip';import {libraryRouter,createLibrary} from '../server/library.mjs';import {obliqueFixture,fixtureDicom} from './helpers/obliqueFixture';
const require=createRequire(import.meta.url),{chromium}=require(process.env.IVCS_PLAYWRIGHT_MODULE || 'playwright');
const root=await fs.mkdtemp(path.join(os.tmpdir(),'ivcs-oblique-browser-')),app=express();app.use('/api/library',libraryRouter(root));app.use(express.static(path.resolve('dist')));app.get('*',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const browser=await chromium.launch({headless:true,channel:'msedge',args:['--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+(server.address() as any).port);
 const zip=new JSZip();fixtureDicom(obliqueFixture()).forEach((b,i)=>zip.file('MR_'+i+'.dcm',b));const bytes=await zip.generateAsync({type:'nodebuffer'});
 await page.locator('input[accept=".dcm,.zip"]').setInputFiles({name:'oblique.zip',mimeType:'application/zip',buffer:bytes});await page.waitForFunction(()=>document.querySelector('header')?.textContent?.includes('[AXIAL MPR]'),{},{timeout:60000});
 const library=createLibrary(root),index=await library.list(),entry=index.patients[0].studies[0],opened=await library.open(entry.key);assert.equal(entry.originals,5);assert.ok(opened.selected.sourceVolume);
 await page.locator('#mpr-tab-oneplus2').click();await page.screenshot({path:'build/oblique-mpr.png'});assert.equal(await page.locator('[data-testid^="view-pane-"]').count(),3);await page.locator('#mpr-tab-axial').click();
 const canvas=page.getByTestId('axial-canvas'),box=await canvas.boundingBox();await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height*.5);await page.mouse.down();await page.mouse.move(box!.x+box!.width*.53,box!.y+box!.height*.5,{steps:3});await page.mouse.up();await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForTimeout(1000);
 await page.reload();await page.waitForFunction(()=>document.querySelector('header')?.textContent?.includes('[AXIAL MPR]'),{},{timeout:60000});
 await page.locator('#btn-export-menu').click();await page.locator('#btn-export-dicom-zip').click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Check before exporting',exact:true}).click();await dialog.locator('#btn-confirm-export-monaco').waitFor({timeout:60000});const [download]=await Promise.all([page.waitForEvent('download'),dialog.locator('#btn-confirm-export-monaco').click()]);const exported=await JSZip.loadAsync(await fs.readFile(await download.path()));assert.equal(Object.keys(exported.files).filter(n=>n.endsWith('.dcm')).length,opened.selected.slices.length+6);
 assert.deepEqual(errors,[]);console.log('PASS oblique ZIP import through worker, axial/MPR views, contour save/reopen and ZIP with originals + derived images + RTSTRUCT');
}finally{await browser.close();server.close();}
