import codecs from 'dcmjs-codecs';
import type {DicomSeries,ImageStudy} from '../../src/types';
import {patientPoint} from '../../src/utils/geometry';
export function obliqueFixture():ImageStudy{
 const series:any={id:'oblique-mr',patientId:'SYNTHETIC-OBLIQUE',patientName:'Synthetic^Oblique',modality:'MR',studyDescription:'Synthetic geometry test',seriesDescription:'Oblique MR synthetic',studyInstanceUID:'2.25.16001',seriesInstanceUID:'2.25.16002',frameOfReferenceUID:'2.25.16003',slices:[]};
 for(let z=0;z<5;z++){const s:any={id:'slice-'+z,sopInstanceUID:'2.25.16100.'+(z+1),sopClassUID:'1.2.840.10008.5.1.4.1.1.4',rows:7,cols:8,pixelSpacing:[1,1],sliceThickness:2,sliceIndex:z,sliceLocation:z*2,imagePositionPatient:[10+1.2*z,-20-1.6*z,30],imageOrientationPatient:[.8,.6,0,0,0,1],windowCenter:350,windowWidth:400,rescaleSlope:1,rescaleIntercept:0,minHU:0,maxHU:1000,huData:new Int16Array(56)};
 for(let y=0;y<7;y++)for(let x=0;x<8;x++){const p=patientPoint(s,x,y);s.huData[y*8+x]=Math.round(5*p[0]+10*p[1]+15*p[2]);}series.slices.push(s);}return series;
}
export function fixtureDicom(series:DicomSeries,raw=false){return series.slices.map(s=>{const e:any={_vrMap:{PixelData:'OW'},SpecificCharacterSet:'ISO_IR 192',PatientID:series.patientId,PatientName:series.patientName,StudyInstanceUID:series.studyInstanceUID,SeriesInstanceUID:series.seriesInstanceUID,FrameOfReferenceUID:series.frameOfReferenceUID,Modality:'MR',SeriesDescription:series.seriesDescription,SOPClassUID:s.sopClassUID,SOPInstanceUID:s.sopInstanceUID,Rows:s.rows,Columns:s.cols,PixelSpacing:s.pixelSpacing,SliceThickness:s.sliceThickness,ImagePositionPatient:s.imagePositionPatient,ImageOrientationPatient:s.imageOrientationPatient,PhotometricInterpretation:'MONOCHROME2',SamplesPerPixel:1,BitsAllocated:16,BitsStored:16,HighBit:15,PixelRepresentation:1,WindowCenter:350,WindowWidth:400,PixelData:[s.huData.slice().buffer]};const t=new codecs.Transcoder(e,raw?'1.2.840.10008.1.2':'1.2.840.10008.1.2.1');return new Uint8Array(raw?t.getDicomDataset():t.getDicomPart10());});}
