import {createRequire} from 'node:module';
import express from 'express';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {libraryRouter,createLibrary} from '../server/library.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.argv[2] || 'playwright');
const root=await fs.mkdtemp(path.join(os.tmpdir(),'radcontour-ui-'));
await fs.writeFile(path.join(root,'preferences.json'),JSON.stringify({language:'es'}));
const app=express();app.use('/api/library',libraryRouter(root));app.use(express.static(path.resolve('dist')));app.get('*',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));
const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.on('listening',resolve));
const browser=await chromium.launch({headless:true,channel:'msedge'});
function session(id,name,multiple=false) {
  const slice={id:'slice-'+id,sliceIndex:0,rows:32,cols:32,pixelSpacing:[1,1],sliceThickness:1,sliceLocation:0,imagePositionPatient:[0,0,0],imageOrientationPatient:[1,0,0,0,1,0],huData:Array(1024).fill(0),minHU:0,maxHU:0,windowCenter:40,windowWidth:400,rescaleSlope:1,rescaleIntercept:0};
  slice.sopInstanceUID='1.2.3.'+Number(id)+'.1';slice.sopClassUID='1.2.840.10008.5.1.4.1.1.2';
  const series={studyInstanceUID:'1.2.3.'+Number(id),seriesInstanceUID:'1.2.3.'+Number(id)+'.2',frameOfReferenceUID:'1.2.3.'+Number(id)+'.3',id:'study-'+id,patientId:id,patientName:name,modality:'CT',studyDescription:'Simulación',seriesDescription:'CT pelvis',slices:[slice,{...slice,id:'slice2-'+id,sopInstanceUID:'1.2.3.'+Number(id)+'.5',sliceIndex:1,sliceLocation:1,imagePositionPatient:[0,0,1]},{...slice,id:'slice3-'+id,sopInstanceUID:'1.2.3.'+Number(id)+'.6',sliceIndex:2,sliceLocation:2,imagePositionPatient:[0,0,2]}]};
  const studies=[series];if(multiple)studies.push({...series,id:'mr-'+id,seriesInstanceUID:'1.2.3.'+Number(id)+'.4',modality:'MR',seriesDescription:'MR pelvis',slices:[{...slice,id:'mr-slice-'+id}]});
  return {format:'radcontour-session',version:1,series,studies,rois:[{id:'roi-'+id,name:'PTV '+id,type:'PTV',color:'#ff0000',visible:true,locked:false,opacity:0.5,sliceMasks:{0:Array(1024).fill(id==='001'?1:0)}}],currentSliceIndex:0,activeRoiId:'roi-'+id,windowCenter:40,windowWidth:400,registrationState:{active:false,referenceStudyId:series.id,secondaryStudyId:studies.at(-1).id,transforms:{},voi:{enabled:false,minX:0,maxX:31,minY:0,maxY:31,minSlice:0,maxSlice:0},fusionMode:'blend',fusionOpacity:0.5,checkerboardSize:32,splitPosition:0.5,secondaryWindowCenter:40,secondaryWindowWidth:400,secondaryColorMap:'grayscale'}};
}
try {
  const page=await browser.newPage({viewport:{width:1600,height:1000}}), errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  assert.match(await page.title(),/^IVCS RT/);
  await page.getByRole('button',{name:'Archivo y ayuda',exact:true}).click();await page.locator('#btn-show-help').click();await page.locator('#btn-show-about').click();
  const about=page.locator('#about-ivcs-rt');await about.waitFor();assert.match(await about.innerText(),/Google AI Studio y Chat GPT 6 Astra/);assert.match(await about.innerText(),/\b\d{8}\b/);
  assert.equal(await about.getByRole('link',{name:'react',exact:true}).count(),1);assert.equal(await about.getByRole('link',{name:'dicom-parser',exact:true}).count(),1);
  const notices=await page.request.get(new URL('/third-party-notices.txt',page.url()).href);assert.equal(notices.status(),200);assert.match(await notices.text(),/Node.js/);
  await page.screenshot({path:path.resolve('about-es-preview.png')});await page.locator('#btn-about-back').click();await page.getByRole('button',{name:'Entendido',exact:true}).click();

  const upload=async s=>{await page.locator('input[accept=".json"]').setInputFiles({name:'case.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('status').filter({hasText:'Guardado manual · sin cambios'}).waitFor();};
  await upload(session('001','Pérez^Ana María',true));
  await page.getByRole('button',{name:/Corregistro 3D/}).click();
  await page.getByRole('button',{name:'Guardar grupo en biblioteca'}).click();
  await page.getByRole('button',{name:'Guardar grupo en biblioteca'}).waitFor({state:'hidden'});
  await upload(session('002','Gómez^Luis'));
  await page.getByRole('button',{name:'Biblioteca',exact:true}).click();
  await page.getByRole('textbox',{name:'Filtrar pacientes'}).fill('001 perez MR');
  await page.getByRole('button',{name:/MR pelvis/}).waitFor();
  await page.screenshot({path:path.resolve('library-preview.png')});
  assert.equal(await page.getByRole('button',{name:/002.*series/}).count(),0);
  await page.getByRole('button',{name:/Grupo 1: abrir corregistro guardado/}).first().click();
  await page.locator('#patient-library').waitFor({state:'hidden'});
  await page.waitForFunction(()=>document.body.textContent.includes('PTV 001'));
  await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('status').filter({hasText:'Guardado manual · sin cambios'}).waitFor();
  const library=createLibrary(root),index=await library.list();
  assert.equal(index.patients.length,2);
  assert.equal(index.patients.find(p=>p.id==='001').groups.length,1);
  const a=index.patients.find(p=>p.id==='001').studies[0];
  const saved=await library.open(a.key);assert.equal(saved.state.rois[0].name,'PTV 001');
  await page.reload();await page.waitForFunction(()=>document.body.textContent.includes('PTV 001'));
  let writes=0;page.on('request',req=>{if(req.method()==='PUT' && req.url().endsWith('/session'))writes++;});
  await page.getByRole('button',{name:'Corte Siguiente (Flecha Abajo)'}).click();await page.mouse.move(750,450);await page.mouse.wheel(0,600);await page.waitForTimeout(1000);assert.equal(writes,0);
  await page.keyboard.press('Control+s');await page.waitForTimeout(800);assert.equal(writes,1);assert.notEqual((await library.open(a.key)).state.currentSliceIndex,0);
  await page.locator('#tab-structures').click();await page.getByTitle('Ocultar contorno',{exact:true}).click();
  await page.getByRole('status').filter({hasText:'Cambios sin guardar'}).waitFor();await page.waitForTimeout(500);assert.equal(writes,1);
  await page.keyboard.press('Control+s');await page.getByRole('status').filter({hasText:'Guardado manual · sin cambios'}).waitFor();assert.equal(writes,2);
  await page.getByRole('button',{name:'Biblioteca',exact:true}).click();
  assert.equal(await page.getByRole('link',{name:'Administrar biblioteca ↗'}).getAttribute('href'),'/library');
  const manager=await browser.newPage();await manager.goto(`http://127.0.0.1:${server.address().port}/library`);
  await manager.getByRole('button',{name:'Seleccionar filtrados'}).click();
  await manager.getByRole('button',{name:'Comprobar selección para TPS'}).click();await manager.getByText('Resultado de la comprobación',{exact:true}).waitFor();await manager.getByRole('checkbox',{name:'He revisado las omisiones y diferencias.'}).check();
  const downloading=manager.waitForEvent('download');await manager.getByRole('button',{name:'Descargar ZIP para TPS'}).click();
  const download=await downloading;const JSZip=(await import('jszip')).default;
  const zip=await JSZip.loadAsync(await fs.readFile(await download.path()));
  const report=JSON.parse(await zip.file('informe.json').async('string')).studies;
  assert.equal(report.filter(r=>r.status==='exportado').length,1);assert.equal(report.filter(r=>r.status==='omitido').length,2);
  const dicom=Object.values(zip.files).find(f=>f.name.endsWith('RTSTRUCT.dcm'));assert.ok(dicom);
  const bytes=await dicom.async('nodebuffer');assert.equal(bytes.subarray(128,132).toString(),'DICM');
  await page.getByRole('button',{name:'Biblioteca',exact:true}).click();
  const stale=await browser.newPage();await stale.goto(page.url());await stale.waitForFunction(()=>document.body.textContent.includes('PTV 001'));
  await page.getByRole('button',{name:'Plantillas',exact:true}).click();
  await page.getByRole('textbox',{name:'Estructuras de la plantilla'}).fill('QA_Template | PRV | #aabbcc');
  await page.getByRole('button',{name:'Añadir estructuras',exact:true}).click();
  await page.getByRole('button',{name:'Guardar plantilla local',exact:true}).click();
  await page.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('status').filter({hasText:'Guardado manual · sin cambios'}).waitFor();
  const updated=await library.open(a.key);assert.equal(updated.state.rois.find(r=>r.name==='QA_Template').color,'#aabbcc');
  await stale.keyboard.press('Control+s');await stale.getByText(/Otra ventana guardó una versión más reciente/).waitFor();await stale.close();
  await page.getByRole('button',{name:'Corte Anterior (Flecha Arriba)'}).click();await page.getByRole('button',{name:'Corte Anterior (Flecha Arriba)'}).click();
  await page.getByRole('button',{name:'Copiar contorno',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Copia desde corte'}).fill('2');await page.getByRole('spinbutton',{name:'Copia hasta corte'}).fill('3');
  await page.getByRole('button',{name:'Preparar copia'}).click();await page.getByRole('slider',{name:'Corte de comparación RTSTRUCT'}).waitFor();
  await page.getByRole('button',{name:'Aceptar cambios',exact:true}).click();
  await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('status').filter({hasText:'Guardado manual · sin cambios'}).waitFor();
  const copied=await library.open(a.key);assert.ok(copied.state.rois[0].sliceMasks[1]);assert.ok(copied.state.rois[0].sliceMasks[2]);
  await page.locator('#mpr-tab-triplanar').click();
  assert.equal(await page.locator('#viewport-brush-thickness-hud').count(),0);
  // The actual toolbar button must enable zoom gestures without editing or scrolling slices.
  const axial=page.getByTestId('axial-canvas'),zoomWrites=writes;
  await page.getByRole('button',{name:'Restablecer zoom axial',exact:true}).click();
  const fittedZoom=Number(await axial.getAttribute('data-zoom')),axialSlice=await axial.getAttribute('data-slice-index');
  await page.locator('#btn-contour-tool-zoom').click();
  const bounds=await axial.boundingBox(),ax= bounds.x+bounds.width/2,ay=bounds.y+bounds.height/2;
  await page.mouse.move(ax,ay);await page.mouse.down();await page.mouse.move(ax,ay-50,{steps:5});await page.mouse.up();
  assert.ok(Number(await axial.getAttribute('data-zoom'))>fittedZoom);
  await page.mouse.move(ax,ay);await page.mouse.down();await page.mouse.move(ax,ay+50,{steps:5});await page.mouse.up();
  assert.ok(Math.abs(Number(await axial.getAttribute('data-zoom'))-fittedZoom)<.001);
  await page.mouse.wheel(0,-100);await page.waitForTimeout(100);
  assert.ok(Number(await axial.getAttribute('data-zoom'))>fittedZoom);assert.equal(await axial.getAttribute('data-slice-index'),axialSlice);
  await page.mouse.down({button:'middle'});await page.mouse.move(ax+30,ay+20,{steps:3});await page.mouse.up({button:'middle'});
  assert.notEqual(Number(await axial.getAttribute('data-pan-x')),0);
  await page.getByRole('button',{name:'Restablecer zoom axial',exact:true}).click();
  assert.equal(Number(await axial.getAttribute('data-zoom')),fittedZoom);assert.equal(Number(await axial.getAttribute('data-pan-x')),0);assert.equal(Number(await axial.getAttribute('data-pan-y')),0);
  await page.getByTitle('Maximizar Plano Axial',{exact:true}).click();await page.getByRole('button',{name:'Restablecer zoom axial',exact:true}).click();
  await page.getByTitle('Maximizar Plano Axial',{exact:true}).click();
  assert.equal(writes,zoomWrites);await page.locator('#btn-contour-tool-brush').click();

  const sagittal=page.locator('[data-plane="sagittal"]');await sagittal.getByTitle('Acercar',{exact:true}).click();
  const planeZoom=await sagittal.locator('[data-plane-zoom]').textContent();
  await sagittal.getByText('Sagital',{exact:true}).dblclick();
  assert.equal(await page.locator('[data-plane="sagittal"] [data-plane-zoom]').textContent(),planeZoom);
  await page.locator('[data-plane="sagittal"]').getByText('Sagital',{exact:true}).dblclick();
  await page.getByRole('combobox',{name:'Contenido del cuarto panel'}).waitFor();

  await page.getByRole('combobox',{name:'Contenido del cuarto panel'}).selectOption('compare');
  await page.screenshot({path:path.resolve('workflow-preview.png')});
  await page.getByRole('spinbutton',{name:'Radio del pincel'}).fill('7.5');
  await page.getByTitle('Mostrar contorno',{exact:true}).click();
  await page.getByRole('status').filter({hasText:'Cambios sin guardar'}).waitFor();
  await page.getByRole('button',{name:'Archivo y ayuda',exact:true}).click();await page.locator('#btn-show-help').click();
  await page.getByRole('combobox',{name:'Idioma de la interfaz'}).selectOption('en');
  await page.getByRole('combobox',{name:'Interface language'}).waitFor();
  await page.getByRole('button',{name:'Got it',exact:true}).click();
  await page.getByRole('button',{name:'Save',exact:true}).waitFor();
  await page.getByRole('status').filter({hasText:'Unsaved changes'}).waitFor();
  assert.equal(await page.getByRole('spinbutton',{name:'Brush radius'}).inputValue(),'7.5');
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('status').filter({hasText:'Manual saving · no changes'}).waitFor();
  assert.equal((await library.open(a.key)).state.rois[0].name,'PTV 001');
  await page.getByRole('button',{name:'File and help',exact:true}).click();await page.locator('#btn-show-help').click();await page.locator('#btn-show-about').click();
  await page.getByRole('dialog',{name:'About IVCS RT'}).waitFor();assert.match(await page.locator('#about-ivcs-rt').innerText(),/vibe-coded with help from Google AI Studio and Chat GPT 6 Astra/);
  await page.screenshot({path:path.resolve('about-en-preview.png')});await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('combobox',{name:'Fourth panel content'}).selectOption('detail');
  await page.screenshot({path:path.resolve('interface-en-preview.png')});
  await page.reload();await page.getByRole('button',{name:'Save',exact:true}).waitFor();
  await page.getByRole('button',{name:'File and help',exact:true}).click();await page.locator('#btn-show-help').click();
  await page.getByRole('combobox',{name:'Interface language'}).selectOption('es');await page.getByRole('button',{name:'Entendido',exact:true}).click();

  manager.on('dialog',d=>d.accept());
  await manager.getByRole('button',{name:'Eliminar estudio',exact:true}).first().click();
  await manager.getByRole('status').filter({hasText:'Eliminado'}).waitFor();
  await manager.getByRole('button',{name:'Papelera (1)'}).click();await manager.getByRole('button',{name:'Restaurar',exact:true}).click();
  await manager.getByRole('status').filter({hasText:'Restaurado'}).waitFor();
  await manager.getByRole('button',{name:'Volver a pacientes'}).click();
  await manager.getByRole('button',{name:'Eliminar paciente',exact:true}).last().click();
  await manager.getByRole('status').filter({hasText:'Eliminado'}).waitFor();
  assert.equal((await library.list()).patients.length,1);
  await manager.screenshot({path:path.resolve('library-manager-preview.png')});
  assert.deepEqual(errors,[]);
  console.log('PASS: patient/session import, flexible search, study submenu, explicit registration group, patient switching and reload with isolated local files.');
} finally {await browser.close();await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});}


