import {tr} from '../i18n';
import React,{useEffect,useRef,useState} from 'react';
import type {ImageStudy,RegistrationState,RegistrationTransform,DicomSlice} from '../types';
import {libraryIndex,loadSecondaryStudy,LibraryStudy} from '../utils/libraryClient';
import {identity3d,volumeCenter,fitLandmarks,LandmarkPair,Vec3,resamplePlane} from '../utils/rigid3d';
import {patientPoint} from '../utils/geometry';
import {renderSliceToCanvas} from '../utils/registrationEngine';
import {compute} from '../utils/computeClient';

function PointPicker({study,label,onPoint,overlay,transform}:{key?:string;study:ImageStudy;label:string;onPoint?:(p:Vec3)=>void;overlay?:ImageStudy;transform?:RegistrationTransform}){
  const [z,setZ]=useState(Math.floor(study.slices.length/2)),canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const s=study.slices[Math.min(z,study.slices.length-1)],c=canvas.current;if(!s || !c)return;
    c.width=s.cols;c.height=Math.round(s.rows*s.pixelSpacing[0]/s.pixelSpacing[1]);const ctx=c.getContext('2d')!;ctx.drawImage(renderSliceToCanvas(s,s.windowCenter,s.windowWidth,'grayscale'),0,0,c.width,c.height);
    if(overlay && transform){const plane=resamplePlane(s,overlay,transform),layer=renderSliceToCanvas(plane,s.windowCenter,s.windowWidth,'cyan');ctx.globalAlpha=.45;ctx.drawImage(layer,0,0,c.width,c.height);ctx.globalAlpha=1;}
  },[study,z,overlay,transform]);
  const s=study.slices[Math.min(z,study.slices.length-1)];
  return <div className="min-w-0 flex-1"><p className="text-xs mb-1">{label}{" "}{tr("· corte")}{" "}{z+1}</p><canvas ref={canvas} className="w-full max-h-72 object-contain bg-black cursor-crosshair" style={{aspectRatio:s.cols*s.pixelSpacing[1]/(s.rows*s.pixelSpacing[0])}} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const ratio=(s.cols*s.pixelSpacing[1])/(s.rows*s.pixelSpacing[0]),w=Math.min(rect.width,rect.height*ratio),h=w/ratio,x=(e.clientX-rect.left-(rect.width-w)/2)/w*s.cols-.5,y=(e.clientY-rect.top-(rect.height-h)/2)/h*s.rows-.5;if(x>=-.5 && y>=-.5 && x<s.cols-.5 && y<s.rows-.5)onPoint?.(patientPoint(s,x,y));}}/><input aria-label={tr("Corte ")+label} type="range" min={0} max={study.slices.length-1} value={z} onChange={e=>setZ(Number(e.target.value))} className="w-full"/></div>;
}
interface Props{onSaveGroup?:()=>void;isOpen:boolean;onClose:()=>void;studies:ImageStudy[];registrationState:RegistrationState;onUpdateRegistrationState:(fn:(p:RegistrationState)=>RegistrationState)=>void;onStudyLoaded?:(s:ImageStudy)=>void;currentSliceIndex:number;currentSlice:DicomSlice|null;activeRoiName?:string;onFitVoiToCurrentSlice:()=>void;}
export function RegistrationModal({studies,registrationState:r,onUpdateRegistrationState:update,onStudyLoaded,onClose,onSaveGroup}:Props){
  const ref=studies.find(s=>s.id===r.referenceStudyId) || studies[0],sec=studies.find(s=>s.id===r.secondaryStudyId);
  const [entries,setEntries]=useState<LibraryStudy[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(''),[tab,setTab]=useState('manual');
  const [pairs,setPairs]=useState<LandmarkPair[]>([]),[fixed,setFixed]=useState<Vec3|null>(null),[moving,setMoving]=useState<Vec3|null>(null),[proposal,setProposal]=useState<any>(null),abort=useRef<AbortController|null>(null);
  useEffect(()=>{libraryIndex().then(i=>setEntries(i.patients.find(p=>p.id===ref?.patientId)?.studies || [])).catch(e=>setError(e.message));return()=>abort.current?.abort();},[]);
  if(!ref)return null;
  const t=r.transforms[sec?.id || '']?.model==='rigid3d'?r.transforms[sec!.id]:identity3d(sec?volumeCenter(sec):[0,0,0]);
  const apply=(value:RegistrationTransform)=>{setProposal(null);if(sec)update(p=>({...p,active:true,transforms:{...p.transforms,[sec.id]:value}}));};
  const choose=async(id:string)=>{setBusy(true);setError('');setProposal(null);setPairs([]);setFixed(null);setMoving(null);try{let s=studies.find(s=>s.id===id);if(!s){const entry=entries.find(e=>e.id===id)!;s=await loadSecondaryStudy(entry.key);onStudyLoaded?.(s);}update(p=>({...p,secondaryStudyId:id,active:false}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const runAuto=async()=>{if(!sec)return;setBusy(true);setError('');setProposal(null);abort.current=new AbortController();try{const result=await compute('registration',[ref,sec,t],{signal:abort.current.signal,progress:p=>setProgress(`${p.percent}% · puntuación ${Number(p.score).toFixed(4)}`)});setProposal(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);setProgress('');}};
  const button='rounded border border-zinc-600 px-3 py-1.5 hover:bg-zinc-800 disabled:opacity-40';
  return <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-3"><section className="bg-zinc-950 text-zinc-200 border border-zinc-600 rounded-xl w-full max-w-5xl max-h-[95vh] overflow-auto p-4 space-y-3">
    <header className="flex justify-between"><div><h2 className="font-semibold">{" "}{tr("Corregistro rígido 3D")}{" "}</h2><p className="text-xs text-zinc-400">{" "}{tr("Referencia:")}{" "}{ref.seriesDescription}{" "}{tr("· Coordenadas físicas DICOM · Sin escalamiento")}{" "}</p></div><button className={button} disabled={busy} onClick={onClose}>{" "}{tr("Cerrar")}{" "}</button></header>
    <label className="block text-xs">{" "}{tr("Imagen secundaria")}{" "}<select aria-label={tr("Imagen secundaria")} className="bg-zinc-800 p-2 ml-2" disabled={busy} value={sec?.id===ref.id?'':sec?.id || ''} onChange={e=>void choose(e.target.value)}><option value="" disabled>{" "}{tr("Seleccione una serie")}{" "}</option>{[...entries.filter(e=>e.id!==ref.id).map(e=>({id:e.id,name:e.description})),...studies.filter(s=>s.id!==ref.id && !entries.some(e=>e.id===s.id)).map(s=>({id:s.id,name:s.seriesDescription}))].map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
    <div className="flex gap-2">{[["manual",tr("Manual")],["points",tr("Puntos anatómicos")],["auto",tr("Automático local")]].map(([id,label])=><button key={id} disabled={busy} className={button+(tab===id?' bg-blue-950':'')} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {error && <p role="alert" className="text-red-300">{" "}{tr(error)}{" "}</p>}
    {sec && sec.id!==ref.id && <>
      {tab==='manual' && <><div className="grid grid-cols-3 gap-3">{[["translationX",tr("Traslación X (mm)")],["translationY",tr("Traslación Y (mm)")],["translationZ",tr("Traslación Z (mm)")],["rotationX",tr("Rotación X (°)")],["rotationY",tr("Rotación Y (°)")],["rotationDeg",tr("Rotación Z (°)")]].map(([key,label])=><label key={key} className="text-xs">{label}<input aria-label={label} disabled={busy || t.locked} type="number" step="0.1" value={t[key] || 0} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value))apply({...t,[key]:value});}} className="block bg-zinc-800 w-full p-2 mt-1"/></label>)}</div><div className="flex gap-2"><button className={button} onClick={()=>apply({...t,locked:!t.locked})}>{t.locked?tr("Desbloquear"):tr("Bloquear transformación")}</button><button className={button} disabled={t.locked} onClick={()=>apply(identity3d(volumeCenter(sec)))}>{" "}{tr("Identidad DICOM")}{" "}</button><button className={button} disabled={t.locked} onClick={()=>{const a=volumeCenter(ref),b=volumeCenter(sec);apply({...identity3d(b),translationX:a[0]-b[0],translationY:a[1]-b[1],translationZ:a[2]-b[2]});}}>{" "}{tr("Alinear centros")}{" "}</button></div></>}
      {tab==='points' && <><p className="text-xs text-zinc-400">{" "}{tr("Seleccione la misma referencia anatómica en ambas imágenes y añada el par. Use al menos tres puntos no alineados, distribuidos en el volumen.")}{" "}</p><div className="flex gap-3"><PointPicker study={ref} label="Referencia" onPoint={setFixed}/><PointPicker key={sec.id} study={sec} label="Secundaria" onPoint={setMoving}/></div><p className="text-xs">{" "}{tr("Referencia:")}{" "}{fixed?.map(v=>v.toFixed(2)).join(', ') || tr("pendiente")}{" "}{tr("· Secundaria:")}{" "}{moving?.map(v=>v.toFixed(2)).join(', ') || tr("pendiente")}{" "}{tr("mm")}{" "}</p><button className={button} disabled={!fixed || !moving || busy} onClick={()=>{setPairs([...pairs,{fixed:fixed!,moving:moving!}]);setFixed(null);setMoving(null);setProposal(null);}}>{" "}{tr("Añadir par")}{" "}</button>{pairs.map((p,i)=><div key={i} className="text-xs flex gap-3"><span>{" "}{tr("Par")}{" "}{i+1}: {p.fixed.map(v=>v.toFixed(1)).join(', ')} ↔ {p.moving.map(v=>v.toFixed(1)).join(', ')}{" "}{tr("mm")}{" "}{proposal?.errors && tr("· error {0} mm", [proposal.errors[i].toFixed(2)])}</span><button onClick={()=>{setPairs(pairs.filter((_,j)=>j!==i));setProposal(null);}}>{" "}{tr("Quitar")}{" "}</button></div>)}<button className={button} disabled={pairs.length<3 || t.locked} onClick={()=>{try{setError('');setProposal(fitLandmarks(pairs));}catch(e){setError((e as Error).message);}}}>{" "}{tr("Calcular por puntos")}{" "}</button></>}
      {tab==='auto' && <><p className="text-xs text-zinc-400">{" "}{tr("Función experimental; requiere revisión visual. Información mutua normalizada sobre el volumen, seis parámetros y refinamiento de grueso a fino. Parte de la transformación actual. Compruebe la alineación inicial y revise la propuesta antes de aceptarla.")}{" "}</p><button className={button} disabled={busy || t.locked} onClick={()=>void runAuto()}>{" "}{tr("Calcular registro automático 3D")}{" "}</button>{busy && <button className={button} onClick={()=>abort.current?.abort()}>{" "}{tr("Cancelar cálculo")}{" "}</button>}<p role="status">{" "}{tr(progress)}{" "}</p></>}
      {proposal && <div className="border border-blue-700 p-3 rounded"><p>{proposal.rms!==undefined?tr("Error RMS de puntos: {0} mm", [proposal.rms.toFixed(2)]):tr("Puntuación NMI: {0}", [proposal.score.toFixed(4)])}{" "}{tr("· Propuesta pendiente")}{" "}</p><button className={button} disabled={busy || t.locked} onClick={()=>{apply(proposal.transform);setProposal(null);}}>{" "}{tr("Aceptar transformación")}{" "}</button><button className={button} onClick={()=>setProposal(null)}>{" "}{tr("Descartar propuesta")}{" "}</button></div>}
      {(tab!=='points' || proposal) && <PointPicker study={ref} label={proposal?'Vista previa de la propuesta':'Fusión 3D sobre referencia'} overlay={sec} transform={proposal?.transform || t}/>}
      <div className="flex flex-wrap gap-3 items-center text-xs"><label><input type="checkbox" checked={r.active} onChange={e=>update(p=>({...p,active:e.target.checked,transforms:{...p.transforms,[sec.id]:t}}))}/>{" "}{tr("Mostrar fusión en visor")}{" "}</label><label>{" "}{tr("Modo")}{" "}<select className="bg-zinc-800 p-1" value={r.fusionMode} onChange={e=>update(p=>({...p,fusionMode:e.target.value as any}))}><option value="blend">{" "}{tr("Mezcla")}{" "}</option><option value="checkerboard">{" "}{tr("Damero")}{" "}</option><option value="split_horizontal">{" "}{tr("Cortina")}{" "}</option><option value="difference">{" "}{tr("Diferencia")}{" "}</option></select></label><label>{" "}{tr("Centro secundario")}{" "}<input aria-label={tr("Centro de ventana secundaria")} type="number" className="bg-zinc-800 w-20" value={r.secondaryWindowCenter} onChange={e=>update(p=>({...p,secondaryWindowCenter:Number(e.target.value)}))}/></label><label>{" "}{tr("Ancho secundario")}{" "}<input aria-label={tr("Ancho de ventana secundaria")} type="number" min="1" className="bg-zinc-800 w-20" value={r.secondaryWindowWidth} onChange={e=>update(p=>({...p,secondaryWindowWidth:Math.max(1,Number(e.target.value))}))}/></label><label>{" "}{tr("Opacidad")}{" "}<input type="range" min="0" max="1" step="0.05" value={r.fusionOpacity} onChange={e=>update(p=>({...p,fusionOpacity:Number(e.target.value)}))}/></label><button className={button} disabled={busy} onClick={onSaveGroup}>{" "}{tr("Guardar grupo en biblioteca")}{" "}</button></div>
    </>}
  </section></div>;
}

