import {secondaryDisplay} from '../utils/fusionDisplay';
import {MprOrthogonalView} from './MprOrthogonalView';
import React,{lazy,Suspense,useEffect,useRef,useState} from 'react';
import type {DicomSeries,ImageStudy,MprCoordinates,StructureRoi,RegistrationState} from '../types';
import {referencePlane,planeMask,ImagePlane} from '../utils/panelPlane';
import {renderSliceToCanvas} from '../utils/registrationEngine';
import {resamplePlane,identity3d,volumeCenter} from '../utils/rigid3d';
import {tr} from '../i18n';
const Contours3D=lazy(()=>import('./Contours3D'));
export interface PaneConfig {plane:ImagePlane|'3d'|'controls'|'detail';mode:string;secondaryId?:string;}
export const defaultPanes:PaneConfig[]=[{plane:'axial',mode:'reference'},{plane:'sagittal',mode:'reference'},{plane:'coronal',mode:'reference'},{plane:'detail',mode:'reference'}];
interface Props {showCrosshairs?:boolean;onToggleCrosshairs?:()=>void;onActivate?:(p:ImagePlane)=>void;config:PaneConfig;onChange:(p:PaneConfig)=>void;index:number;series:DicomSeries|null;studies:ImageStudy[];coordinates:MprCoordinates;onNavigate:(p:Partial<MprCoordinates>)=>void;rois:StructureRoi[];activeRoiId?:string;registration?:RegistrationState;windowCenter:number;windowWidth:number;controls:React.ReactNode;editor?:React.ReactNode;detailPlane:ImagePlane;}
export function ConfigurablePane(props:Props){
 const {config,onChange,index,series,studies,registration,editor,controls}=props;
 const secondary=studies.filter(s=>s.id!==registration?.referenceStudyId && s.slices!==series?.slices && (registration?.transforms[s.id]?.model==='rigid3d' || (!!s.frameOfReferenceUID && s.frameOfReferenceUID===series?.frameOfReferenceUID)));
 const picked=secondary.find(s=>s.id===(config.secondaryId || registration?.secondaryStudyId)) || secondary[0];
 const plane=config.plane==='detail'?props.detailPlane:config.plane;
 return <section className="flex flex-col flex-1 min-h-0 min-w-0 overflow-hidden bg-black border border-zinc-800" data-testid={'view-pane-'+index} onPointerEnter={()=>{if(['axial','coronal','sagittal'].includes(config.plane))props.onActivate?.(config.plane as ImagePlane);}}><header className="flex items-center flex-wrap gap-1 text-xs bg-zinc-950 p-1 shrink-0"><select aria-label={tr('Contenido del panel')+' '+(index+1)} className="bg-zinc-800 rounded max-w-full" value={config.plane} onChange={e=>onChange({...config,plane:e.target.value as PaneConfig['plane']})}>{[['axial','Axial'],['coronal','Coronal'],['sagittal','Sagital'],['detail','Detalle del plano activo'],['3d','Contornos 3D'],['controls','Controles']].map(([v,label])=><option key={v} value={v}>{tr(label)}</option>)}</select>{plane!=='3d' && plane!=='controls' && <><select aria-label={tr('Modo del panel')+' '+(index+1)} value={config.mode} className="bg-zinc-800 rounded" onChange={e=>onChange({...config,mode:e.target.value})}>{[['reference','Referencia'],['secondary','Secundaria alineada'],['blend','Fusión'],['compare','Comparar secundaria'],['checkerboard','Tablero'],['split_horizontal','División izquierda/derecha'],['split_vertical','División superior/inferior'],['difference','Diferencia']].map(([v,label])=><option key={v} value={v} disabled={v!=='reference' && !picked}>{tr(label)}</option>)}</select>{config.mode!=='reference' && <select aria-label={tr('Imagen secundaria')+' '+(index+1)} className="bg-zinc-800 max-w-40" value={picked?.id || ''} onChange={e=>onChange({...config,secondaryId:e.target.value})}>{secondary.map(s=><option key={s.id} value={s.id}>{s.modality} · {s.seriesDescription}</option>)}</select>}</>}</header>
 {plane==='3d'?(series?<Suspense fallback={<p>{tr('Cargando vista 3D…')}</p>}><Contours3D series={series} rois={props.rois} activeRoiId={props.activeRoiId}/></Suspense>:null):plane==='controls'?controls:editor || ((plane==='coronal' || plane==='sagittal') && config.mode==='reference'?<MprOrthogonalView plane={plane} series={series} coordinates={props.coordinates} onNavigateCoordinates={props.onNavigate} windowCenter={props.windowCenter} windowWidth={props.windowWidth} rois={props.rois} activeRoiId={props.activeRoiId} onActivate={props.onActivate} showCrosshairs={props.showCrosshairs} onToggleCrosshairs={props.onToggleCrosshairs}/>:<PaneImage {...props} plane={plane as ImagePlane} secondary={picked}/>)}
 </section>;
}
function PaneImage({series,coordinates,rois,registration,windowCenter,windowWidth,config,plane,secondary,onNavigate}:Props & {plane:ImagePlane;secondary?:ImageStudy}){
 const canvas=useRef<HTMLCanvasElement>(null),host=useRef<HTMLDivElement>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 useEffect(()=>{const el=host.current;if(!el)return;const stop=(e:WheelEvent)=>e.preventDefault();el.addEventListener('wheel',stop,{passive:false});return()=>el.removeEventListener('wheel',stop);},[]);
 useEffect(()=>{const c=canvas.current;if(!c || !series)return;const slice=referencePlane(series,coordinates,plane),base=renderSliceToCanvas(slice,windowCenter,windowWidth,'grayscale'),mode=config.mode;
 let overlay:HTMLCanvasElement|undefined;if(secondary && mode!=='reference'){const t=registration?.transforms[secondary.id];overlay=renderSliceToCanvas(resamplePlane(slice,secondary,t?.model==='rigid3d'?t:identity3d(volumeCenter(secondary))),(secondary.id===registration?.secondaryStudyId?registration.secondaryWindowCenter:secondaryDisplay(secondary).secondaryWindowCenter),(secondary.id===registration?.secondaryStudyId?registration.secondaryWindowWidth:secondaryDisplay(secondary).secondaryWindowWidth),registration?.secondaryColorMap || 'grayscale');}
 c.width=base.width*(mode==='compare'?2:1);c.height=Math.max(1,Math.round(base.height*slice.pixelSpacing[0]/slice.pixelSpacing[1]));const ctx=c.getContext('2d')!;ctx.scale(1,c.height/base.height);ctx.drawImage(base,0,0);
 if(overlay){ctx.save();if(mode==='compare')ctx.drawImage(overlay,base.width,0);else if(mode==='secondary'){ctx.clearRect(0,0,base.width,base.height);ctx.drawImage(overlay,0,0);}else{
 if(mode==='blend')ctx.globalAlpha=registration?.fusionOpacity ?? .5;
 if(mode==='difference')ctx.globalCompositeOperation='difference';
 if(mode==='checkerboard'){const size=registration?.checkerboardSize || 32;ctx.beginPath();for(let y=0;y<base.height;y+=size)for(let x=0;x<base.width;x+=size)if((Math.floor(x/size)+Math.floor(y/size))%2===0)ctx.rect(x,y,size,size);ctx.clip();}
 if(mode.startsWith('split_')){const position=registration?.splitPosition ?? .5;ctx.beginPath();mode==='split_horizontal'?ctx.rect(base.width*position,0,base.width,base.height):ctx.rect(0,base.height*position,base.width,base.height);ctx.clip();}
 ctx.drawImage(overlay,0,0);}ctx.restore();}
 for(const roi of rois.filter(r=>r.visible)){const mask=planeMask(series,coordinates,plane,roi);if(!mask)continue;ctx.globalAlpha=roi.opacity;ctx.fillStyle=roi.color;for(let i=0;i<mask.length;i++)if(mask[i])ctx.fillRect(i%slice.cols,Math.floor(i/slice.cols),1,1);}ctx.globalAlpha=1;
 },[series,coordinates,plane,rois,registration,windowCenter,windowWidth,config.mode,secondary]);
 const s=series?.slices[0],aspect=s?(plane==='axial'?s.cols*s.pixelSpacing[1]/(s.rows*s.pixelSpacing[0]):plane==='coronal'?s.cols*s.pixelSpacing[1]/(series!.slices.length*(series!.slices.length>1?Math.abs(series!.slices[1].sliceLocation-s.sliceLocation):s.sliceThickness)):s.rows*s.pixelSpacing[0]/(series!.slices.length*(series!.slices.length>1?Math.abs(series!.slices[1].sliceLocation-s.sliceLocation):s.sliceThickness)))*(config.mode==='compare'?2:1):1;
 return <><div className="text-xs flex gap-2 px-2 text-zinc-400"><span>{tr('Visualización · rueda: cortes · Ctrl+rueda: zoom · arrastrar: desplazar')}</span><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>{tr('Restablecer vista')}</button></div>{config.mode!=='reference' && !secondary && <p className="text-amber-300 text-xs">{tr('Seleccione una imagen corregistrada.')}</p>}<div ref={host} className="relative flex-1 min-h-0 overflow-hidden flex items-center justify-center touch-none" onWheel={e=>{e.stopPropagation();if(e.ctrlKey){setZoom(z=>Math.max(.2,Math.min(10,z*Math.exp(-e.deltaY*.002))));return;}if(!series)return;const key=plane==='axial'?'z':plane==='coronal'?'y':'x',limit=key==='z'?series.slices.length:key==='y'?s!.rows:s!.cols;onNavigate({[key]:Math.max(0,Math.min(limit-1,coordinates[key]+Math.sign(e.deltaY)))});}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}} onPointerMove={e=>{if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <span className="absolute top-1 left-1/2 z-10 text-xs text-cyan-400 pointer-events-none">{plane==='axial'?'A':'S'}</span><span className="absolute bottom-1 left-1/2 z-10 text-xs text-cyan-400 pointer-events-none">{plane==='axial'?'P':'I'}</span><span className="absolute left-1 top-1/2 z-10 text-xs text-cyan-400 pointer-events-none">{plane==='sagittal'?'A':'R'}</span><span className="absolute right-1 top-1/2 z-10 text-xs text-cyan-400 pointer-events-none">{plane==='sagittal'?'P':'L'}</span>
 <canvas ref={canvas} style={{aspectRatio:String(aspect),width:'100%',height:'100%',objectFit:'contain',transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}/>
 </div></>;
}
