import {getPreferences,savePreferences} from '../utils/libraryClient';
import {tr} from '../i18n';
import React,{useEffect,useRef,useState} from 'react';
import type {DicomSeries,ImageStudy,MprCoordinates,StructureRoi,RegistrationState} from '../types';
import {renderSliceToCanvas} from '../utils/registrationEngine';
import {getVolumeGeometry,renderCoronalSliceToCanvas,renderSagittalSliceToCanvas} from '../utils/mprEngine';
import {resamplePlane,identity3d,volumeCenter} from '../utils/rigid3d';
export function FourthPane({series,coordinates,plane,windowCenter,windowWidth,rois,activeRoi,secondary,registration,controls}:{series:DicomSeries|null;coordinates:MprCoordinates;plane:'axial'|'coronal'|'sagittal';windowCenter:number;windowWidth:number;rois:StructureRoi[];activeRoi:StructureRoi|null;secondary?:ImageStudy;registration?:RegistrationState;controls:React.ReactNode}){
 const [mode,setMode]=useState('detail'),canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{getPreferences().then(p=>{if(['detail','compare','controls'].includes(p.fourthPane))setMode(p.fourthPane);}).catch(()=>{});},[]);
 useEffect(()=>{if(mode==='compare' && (!secondary || secondary.id===registration?.referenceStudyId))setMode('detail');},[mode,secondary,registration?.referenceStudyId]);
 useEffect(()=>{const c=canvas.current;if(!c || !series || mode==='controls')return;const s=series.slices[coordinates.z];if(!s)return;
 const opts={windowCenter,windowWidth,rois,showRois:true,activeRoiId:activeRoi?.id};
 const base=plane==='coronal' && mode==='detail'?renderCoronalSliceToCanvas(series,coordinates.y,opts):plane==='sagittal' && mode==='detail'?renderSagittalSliceToCanvas(series,coordinates.x,opts):renderSliceToCanvas(s,windowCenter,windowWidth,'grayscale');
 const h=plane==='axial' || mode==='compare'?Math.round(base.height*s.pixelSpacing[0]/s.pixelSpacing[1]):Math.round(base.width*(plane==='coronal'?getVolumeGeometry(series).coronalAspect:getVolumeGeometry(series).sagittalAspect));c.width=base.width*(mode==='compare'?2:1);c.height=h;const ctx=c.getContext('2d')!;ctx.drawImage(base,0,0,base.width,h);
 if(mode==='detail' && plane==='axial'){for(const roi of rois.filter(r=>r.visible)){const mask=roi.sliceMasks[coordinates.z];if(!mask)continue;ctx.fillStyle=roi.color;ctx.globalAlpha=roi.opacity;for(let i=0;i<mask.length;i++)if(mask[i])ctx.fillRect(i%s.cols,Math.floor(i/s.cols)*h/s.rows,1,h/s.rows);ctx.globalAlpha=1;}}
 if(mode==='compare' && secondary && secondary.id!==registration?.referenceStudyId){const transform=registration?.transforms[secondary.id];const aligned=resamplePlane(s,secondary,transform?.model==='rigid3d'?transform:identity3d(volumeCenter(secondary)));ctx.drawImage(renderSliceToCanvas(aligned,registration?.secondaryWindowCenter || windowCenter,registration?.secondaryWindowWidth || windowWidth,'grayscale'),base.width,0,base.width,h);}
 },[series,coordinates,plane,mode,windowCenter,windowWidth,rois,activeRoi,secondary,registration]);
 return <section className="flex flex-col min-h-0 min-w-0 bg-black border border-zinc-800"><header className="flex gap-2 items-center h-8 px-2 bg-zinc-950 text-xs shrink-0"><label>{" "}{tr("Cuarto panel")}{" "}<select aria-label={tr("Contenido del cuarto panel")} className="bg-zinc-800 rounded" value={mode} onChange={e=>{setMode(e.target.value);void savePreferences({fourthPane:e.target.value}).catch(()=>{});}}><option value="detail">{" "}{tr("Detalle del plano activo")}{" "}</option><option value="compare" disabled={!secondary || secondary.id===registration?.referenceStudyId}>{" "}{tr("Comparar secundaria")}{" "}</option><option value="controls">{" "}{tr("Controles")}{" "}</option></select></label></header>{mode==='controls'?controls:<><p className="text-xs px-2 py-1 text-zinc-400">{mode==='compare'?tr("Referencia · Secundaria alineada"):({axial:tr("Axial"),coronal:tr("Coronal"),sagittal:tr("Sagital")})[plane]}</p><div className="flex-1 min-h-0 flex items-center justify-center overflow-hidden"><canvas ref={canvas} className="w-full h-full object-contain"/></div></>}</section>;
}
