import test from 'node:test';import assert from 'node:assert/strict';import {promises as fs} from 'node:fs';import os from 'node:os';import path from 'node:path';import codecs from 'dcmjs-codecs';import dp from 'dicom-parser';import JSZip from 'jszip';
import type {DicomSeries,ImageStudy} from '../src/types';import {acquisitionGeometry,volumeSampler,physicalCenter} from '../src/utils/volumeSampling';import {resampleAxial} from '../src/utils/axialResampling';import {patientPoint,validateVolume} from '../src/utils/geometry';import {parseMultipleDicomFiles,parseDicomByteArray} from '../src/utils/dicomParser';import {derivedDicomImages} from '../src/utils/derivedDicom';import {samplePhysical,identity3d} from '../src/utils/rigid3d';import {createLibrary} from '../server/library.mjs';import {checkedOriginals,buildDicomBundle} from '../src/utils/dicomBundle';import {defaultRegistration} from '../src/utils/libraryClient';import {parseSession,serializeSession} from '../src/utils/session';import {exportMonacoRtStruct} from '../src/utils/monacoRtStructExporter';
import {obliqueFixture,fixtureDicom} from './helpers/obliqueFixture';
test('oblique physical sampler exactly preserves lattice values and linear interpolation in LPS',()=>{
 const s=obliqueFixture(),sample=volumeSampler(s);acquisitionGeometry(s.slices);
 for(let z=0;z<5;z++)for(let y=0;y<7;y++)for(let x=0;x<8;x++){const p=patientPoint(s.slices[z],x,y);assert.ok(Math.abs(sample(...p)!-s.slices[z].huData[y*8+x])<1e-8);}
 const p=patientPoint(s.slices[2],2.25,3.5);assert.ok(Math.abs(sample(...p)!-(5*p[0]+10*p[1]+15*p[2]))<1e-8);assert.equal(sample(1000,1000,1000),null);
 const center=physicalCenter(s),a=patientPoint(s.slices[0],3.5,3),b=patientPoint(s.slices[4],3.5,3);assert.deepEqual(center,a.map((v,i)=>(v+b[i])/2));
 const bad=obliqueFixture();bad.slices[2].imageOrientationPatient=[1,0,0,0,1,0];assert.throws(()=>acquisitionGeometry(bad.slices),/paralelos/);
 const gap=obliqueFixture();gap.slices[3].imagePositionPatient![0]+=2;assert.throws(()=>acquisitionGeometry(gap.slices),/irregular/);
});
test('axial reconstruction has stable new UIDs, padding support and uses native source for registration',async()=>{
 const source=obliqueFixture(),copy=source.slices.map(s=>s.huData.slice()),axial=await resampleAxial(source),again=await resampleAxial(source);validateVolume(axial.slices);assert.equal(axial.seriesInstanceUID,again.seriesInstanceUID);assert.notEqual(axial.seriesInstanceUID,source.seriesInstanceUID);assert.equal(axial.frameOfReferenceUID,source.frameOfReferenceUID);assert.equal(axial.sourceVolume,source);
 assert.ok(axial.slices.some(s=>s.valid!.some(v=>v===0)));assert.ok(axial.slices.some(s=>s.valid!.some(v=>v===1)));
 for(const s of axial.slices)for(let y=0;y<s.rows;y++)for(let x=0;x<s.cols;x++){const i=y*s.cols+x,p=patientPoint(s,x,y),v=samplePhysical(source,p);assert.equal(s.valid![i],v===null?0:1);assert.equal(s.huData[i],v===null?-32768:Math.round(v));}
 const p=patientPoint(source.slices[2],2.25,3.5);assert.equal(samplePhysical(axial,p),samplePhysical(source,p));assert.deepEqual(source.slices.map(s=>s.huData),copy);
 await assert.rejects(resampleAxial(source,undefined,.001),/memoria/);
 const session:any={format:'radcontour-session',version:1,series:axial,studies:[{...axial,id:'view'}],rois:[],currentSliceIndex:0,activeRoiId:null,windowCenter:350,windowWidth:400,registrationState:defaultRegistration('view')};const restored=parseSession(serializeSession(session));assert.deepEqual(restored.series.sourceVolume!.slices[0].huData,source.slices[0].huData);assert.deepEqual(restored.series.slices[0].valid,axial.slices[0].valid);
});
test('oblique import, portable original archive and derived DICOM ZIP remain geometrically consistent',async()=>{
 const original=obliqueFixture(),bytes=fixtureDicom(original),files=bytes.map((b,i)=>new File([b],'MR_'+i+'.dcm'));
 const parsed=await parseMultipleDicomFiles(files);assert.ok(parsed.sourceVolume);validateVolume(parsed.slices);
 const originals=new JSZip();bytes.forEach((b,i)=>originals.file(i+'.dcm',b));const archive=await originals.generateAsync({type:'uint8array'});
 const checked=await checkedOriginals(parsed.sourceVolume!,archive);assert.deepEqual(checked,bytes);
 const derived=await derivedDicomImages(parsed,checked);for(let i=0;i<derived.length;i++){const decoded=parseDicomByteArray(derived[i]);assert.deepEqual(decoded.slice.huData,parsed.slices[i].huData);assert.ok(decoded.slice.imagePositionPatient!.every((v,k)=>Math.abs(v-parsed.slices[i].imagePositionPatient![k])<1e-8));assert.equal(dp.parseDicom(derived[i]).int16("x00280120"),-32768);assert.equal(decoded.seriesInfo.seriesInstanceUID,parsed.seriesInstanceUID);assert.equal(decoded.slice.sopInstanceUID,parsed.slices[i].sopInstanceUID);}
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'ivcs-oblique-')),library=createLibrary(root),plain=(v:any)=>JSON.parse(JSON.stringify(v,(_,x)=>x instanceof Int16Array || x instanceof Uint8Array?Array.from(x):x));
 const {key}=await library.putStudy(plain((parsed as any).studies[0]));await library.originals(parsed.patientId,archive,'source.zip');assert.equal((await library.list()).patients[0].studies[0].originals,5);const reparsed=await parseMultipleDicomFiles(bytes.map((b,i)=>new File([b],'renamed_'+i+'.dcm')));assert.equal((await library.putStudy(plain((reparsed as any).studies[0]))).key,key);
 const mask=new Uint8Array(parsed.slices[2].huData.length);const i=parsed.slices[2].valid!.findIndex(v=>v===1);mask[i]=1;const roi:any={id:'r',name:'Test',type:'PTV',visible:true,locked:false,color:'#ff0000',opacity:.5,sliceMasks:{2:mask}};const rt=exportMonacoRtStruct(parsed,[roi]).blob;
 const old=globalThis.fetch;globalThis.fetch=async()=>new Response(archive);try{const zip=await JSZip.loadAsync(await(await buildDicomBundle(parsed,rt,{reference:{key} as any,choices:[]},[],()=>{})).arrayBuffer());assert.equal(Object.keys(zip.files).filter(n=>n.endsWith('.dcm')).length,derived.length+bytes.length+1);const ids=new Set<string>();for(const n of Object.keys(zip.files).filter(n=>n.endsWith('.dcm')))ids.add(dp.parseDicom(await zip.file(n)!.async('uint8array')).string('x00080018')!);for(const s of parsed.slices)assert.ok(ids.has(s.sopInstanceUID!));for(const s of original.slices)assert.ok(ids.has(s.sopInstanceUID!));}finally{globalThis.fetch=old;}
});
test('headerless oblique originals can also produce valid derived Part 10 images',async()=>{const original=obliqueFixture(),bytes=fixtureDicom(original,true),parsed=await parseMultipleDicomFiles(bytes.map((b,i)=>new File([b],i+'.dcm'))),derived=await derivedDicomImages(parsed,bytes);assert.equal(parseDicomByteArray(derived[0]).seriesInfo.seriesInstanceUID,parsed.seriesInstanceUID);});

test('compressed oblique MR reconstructs and exports derived pixels without recompressing originals',async()=>{
 const source=obliqueFixture();await codecs.NativeCodecs.initializeAsync();const bytes=fixtureDicom(source).map(b=>{const t=new codecs.Transcoder(b.slice().buffer);t.transcode('1.2.840.10008.1.2.4.80');return new Uint8Array(t.getDicomPart10());});
 const parsed=await parseMultipleDicomFiles(bytes.map((b,i)=>new File([b],i+'.dcm')));assert.ok(parsed.sourceVolume!.slices.every(s=>s.sourceCompressed));const derived=await derivedDicomImages(parsed,bytes);assert.deepEqual(parseDicomByteArray(derived[2]).slice.huData,parsed.slices[2].huData);assert.equal(dp.parseDicom(derived[2]).string('x00020010'),'1.2.840.10008.1.2.1');
});
