import {test} from 'node:test';import assert from 'node:assert/strict';
import {identity3d,transformPoint,automaticRigid3d} from '../src/utils/rigid3d';
import {compose,inverse,sameTransform,dragTransform,physicalVoi} from '../src/utils/registrationGeometry';
import {applyRelated,linkedRelations,relatedInitial} from '../src/utils/registrationRelations';
import {defaultRegistration} from '../src/utils/libraryClient';
import {referencePlane} from '../src/utils/panelPlane';
function phantom(){return {patientId:'SYNTHETIC',patientName:'Test',modality:'CT',studyDescription:'Test',seriesDescription:'Test',slices:Array.from({length:16},(_,z)=>({id:String(z),sliceIndex:z,rows:32,cols:32,pixelSpacing:[1,1] as [number,number],sliceThickness:1,sliceLocation:z,imagePositionPatient:[0,0,z] as [number,number,number],imageOrientationPatient:[1,0,0,0,1,0] as [number,number,number,number,number,number],huData:Int16Array.from({length:1024},(_,i)=>Math.round(400*Math.exp(-((i%32-10)**2+(Math.floor(i/32)-12)**2+(z-6)**2)/24)+200*Math.exp(-((i%32-22)**2+(Math.floor(i/32)-20)**2+(z-10)**2)/16))),minHU:0,maxHU:600,windowCenter:300,windowWidth:600,rescaleSlope:1,rescaleIntercept:0}))};}
const a={...identity3d([7,-9,11]),rotationX:17,rotationY:28,rotationDeg:-13,translationX:9,translationY:6,translationZ:2};
test('rigid composition and inverse retain physical transforms with nonzero pivots',()=>{assert.ok(sameTransform(compose(a,inverse(a)),identity3d(),1e-8));const b={...identity3d([22,2,-10]),rotationY:89.99,rotationDeg:30,translationX:3};const p:[number,number,number]=[33,14,-9];assert.ok(Math.hypot(...transformPoint(p,compose(a,b)).map((v,i)=>v-transformPoint(transformPoint(p,b),a)[i]))<1e-8);});
test('translation and rotation from each plane follow its world axes and preserve the pivot',()=>{const s=phantom(),c={x:16,y:16,z:8},pivot:[number,number,number]=[16,16,8];for(const plane of ['axial','coronal','sagittal'] as const){const frame=referencePlane(s,c,plane),t=dragTransform(a,frame,3,-4,undefined,pivot),o=frame.imageOrientationPatient!;assert.ok(Math.abs(t.translationZ-a.translationZ-3*o[2]+4*o[5])<1e-8);const r=dragTransform(identity3d(),frame,0,0,Math.PI/2,pivot);assert.ok(Math.hypot(...transformPoint(pivot,r).map((v,i)=>v-pivot[i]))<1e-8);const u=pivot.map((v,i)=>v+o[i]) as [number,number,number];assert.ok(Math.hypot(...transformPoint(u,r).map((v,i)=>v-pivot[i]-o[i+3]))<1e-8);}});
const nodes=[{id:'ct',key:'ct',frameOfReferenceUID:'ct'},{id:'mr1',key:'mr1',frameOfReferenceUID:'mr'},{id:'mr2',key:'mr2',frameOfReferenceUID:'mr'}];
test('native linked series move together, including unloaded metadata members; subsequent selection inherits placement',()=>{const r=defaultRegistration('ct','mr1'),next=applyRelated(r,nodes,[],'mr1',a,'preserve');assert.ok(sameTransform(next.transforms.mr1,next.transforms.mr2));assert.ok(sameTransform(relatedInitial({...next,transforms:{mr1:a}},nodes,[],'mr2'),a));const b=dragTransform(a,referencePlane(phantom(),{x:16,y:16,z:8},'coronal'),0,0,.2,[16,16,8]);const again=applyRelated(next,nodes,[],'mr1',b,'preserve');assert.ok(sameTransform(again.transforms.mr2,b));});
test('saved nonidentity relative transforms are preserved while moving a linked block',()=>{const groups=[{referenceKey:'mr1',transforms:{mr2:{...identity3d([5,5,5]),rotationDeg:12,translationX:4}}}],r=defaultRegistration('ct','mr1');const n=nodes.map(s=>({...s,frameOfReferenceUID:s.id}));const next=applyRelated(r,n,groups,'mr1',a,'preserve');assert.ok(sameTransform(compose(inverse(next.transforms.mr1),next.transforms.mr2),groups[0].transforms.mr2));});
test('fixed reference and locked peers block mutation; explicit detach preserves other series',()=>{const r=defaultRegistration('ct','mr1'),all=nodes.map(s=>({...s,frameOfReferenceUID:'same'}));assert.throws(()=>applyRelated(r,all,[],'mr1',a,'preserve'),/referencia fija/);r.transforms.mr2={...identity3d(),locked:true};assert.throws(()=>applyRelated(r,nodes,[],'mr1',a,'preserve'),/bloqueada/);const next=applyRelated(r,nodes,[],'mr1',a,'single');assert.deepEqual(next.transforms.mr2,r.transforms.mr2);assert.deepEqual(next.detachedSeriesIds,['mr1']);assert.ok(sameTransform(r.transforms.mr2,identity3d()));});
test('inconsistent native and saved graph is detected; explicit source policy resolves it',()=>{const groups=[{referenceKey:'mr1',transforms:{mr2:{...identity3d(),translationX:8}}}],r=defaultRegistration('ct','mr1');assert.ok(linkedRelations(nodes,groups,'mr1','ct').conflicts.length);assert.throws(()=>applyRelated(r,nodes,groups,'mr1',a,'preserve'),/Conflicto/);assert.ok(sameTransform(applyRelated(r,nodes,groups,'mr1',a,'dicom').transforms.mr2,a));assert.ok(sameTransform(applyRelated(r,nodes,groups,'mr1',a,'saved').transforms.mr2,compose(a,groups[0].transforms.mr2)));});
test('missing frame identifiers never create implicit relationships',()=>{const n=nodes.map(s=>({...s,frameOfReferenceUID:undefined}));assert.deepEqual(Object.keys(linkedRelations(n,[],'mr1','ct').toSelected),['mr1']);});
test('VOI uses physical voxel edges and metric progress carries candidate transforms',()=>{const fixed=phantom(),moving={...fixed,slices:fixed.slices.map(s=>({...s,imagePositionPatient:[s.imagePositionPatient[0]+2,s.imagePositionPatient[1]-1,s.imagePositionPatient[2]+1] as [number,number,number]}))};const voi=physicalVoi(fixed,{enabled:true,minX:5,maxX:26,minY:5,maxY:26,minSlice:2,maxSlice:13})!;assert.deepEqual(voi.min,[4.5,4.5,1.5]);assert.deepEqual(voi.max,[26.5,26.5,13.5]);for(const metric of ['nmi_linear','ncc'] as const){const updates:any[]=[],result=automaticRigid3d(fixed,moving,identity3d([16,16,8]),p=>updates.push(p),{voi,metric});assert.ok(Math.hypot(result.transform.translationX+2,result.transform.translationY-1,result.transform.translationZ+1)<1.5,JSON.stringify(result));assert.ok(updates.length>1 && updates.every(p=>p.transform));assert.equal(updates.at(-1).percent,100);}});
test('empty VOI fails without returning a misleading proposal',()=>{const s=phantom();assert.throws(()=>automaticRigid3d(s,s,identity3d(),undefined,{voi:{min:[100,100,100],max:[110,110,110]}}),/muestras/);});

test('smooth mutual information aligns a synthetic nonlinear intensity mapping inside a VOI',()=>{
 const fixed=phantom(),moving={...fixed,modality:'MR',slices:fixed.slices.map(s=>({...s,minHU:0,maxHU:2500,huData:Int16Array.from(s.huData,v=>Math.round(100*Math.sqrt(v))),imagePositionPatient:[2,-1,s.sliceLocation+1] as [number,number,number]}))};
 const result=automaticRigid3d(fixed,moving,identity3d([16,16,8]),undefined,{metric:'nmi_linear',voi:{min:[5,5,2],max:[27,27,14]}});
 assert.ok(Math.hypot(result.transform.translationX+2,result.transform.translationY-1,result.transform.translationZ+1)<1.5,JSON.stringify(result));
});
test('small increments cannot bypass fixed-reference protection or a locked transform',()=>{
 const all=nodes.map(s=>({...s,frameOfReferenceUID:'same'})),r=defaultRegistration('ct','mr1'),tiny={...identity3d(),translationX:.001};
 assert.throws(()=>applyRelated(r,all,[],'mr1',tiny,'preserve'),/referencia fija/);
 r.transforms.mr1={...identity3d(),locked:true};assert.throws(()=>applyRelated(r,nodes,[],'mr1',tiny,'single'),/bloqueada/);
});
